-- ============================================================================
-- [05/05/2026 - Alexandre Carvalho] Tabelas de apoio para Fluxo Previo
-- ============================================================================

CREATE TABLE MEGA.CCS_TB_GFIN_FLX_CONTA (
  AGN_IN_CODIGO  NUMBER          NOT NULL,
  FLX_CH_ATIVO   CHAR(1) DEFAULT 'S' NOT NULL,
  FLX_DT_INC     DATE    DEFAULT SYSDATE,
  CONSTRAINT PK_CCS_TB_GFIN_FLX_CONTA PRIMARY KEY (AGN_IN_CODIGO)
)
/

CREATE TABLE MEGA.CCS_TB_GFIN_FLX_SIM (
  SIM_IN_CODIGO  NUMBER          NOT NULL,
  SIM_DT_DATA    DATE            NOT NULL,
  FIL_IN_CODIGO  NUMBER          NOT NULL,
  SIM_CH_TIPO    CHAR(1)         NOT NULL,
  SIM_RE_VALOR   NUMBER(15,2)    NOT NULL,
  SIM_ST_DESCRICAO VARCHAR2(200),
  SIM_IN_USUARIO NUMBER          NOT NULL,
  SIM_DT_INC     DATE    DEFAULT SYSDATE,
  CONSTRAINT PK_CCS_TB_GFIN_FLX_SIM PRIMARY KEY (SIM_IN_CODIGO),
  CONSTRAINT CK_CCS_TB_GFIN_FLX_SIM_TIPO CHECK (SIM_CH_TIPO IN ('C','D'))
)
/

CREATE SEQUENCE MEGA.CCS_SEQ_GFIN_FLX_SIM START WITH 1 INCREMENT BY 1 NOCACHE
/
