-- [23/07/2026 - CRIADO POR ALEXANDRE CARVALHO] Parametros gerais do Gestor
-- Financeiro (CCS_TB_GFIN_PARAM). Primeira chave: LIB_BAIXA_DIAS_UTEIS
-- (Numero de dias uteis para Baixa, modulo Liberacao de Data de Baixa).
-- Padrao espelho da CCS_TB_GFIN_SCORE_PARAM + auditoria de quem alterou.

-- 1. Tabela (idempotente via deploy: ORA-00955 ignorado) -----------------------
CREATE TABLE MEGA.CCS_TB_GFIN_PARAM (
  PARAM_ST_CHAVE     VARCHAR2(50)  NOT NULL,
  PARAM_RE_VALOR     NUMBER        NOT NULL,
  PARAM_ST_DESCRICAO VARCHAR2(200),
  PARAM_DT_ALTERACAO DATE          DEFAULT SYSDATE,
  PARAM_IN_USU       NUMBER,
  PARAM_ST_USU       VARCHAR2(60),
  CONSTRAINT PK_CCS_TB_GFIN_PARAM PRIMARY KEY (PARAM_ST_CHAVE)
);

-- 2. Seed do parametro (MERGE idempotente; valor inicial 3) --------------------
BEGIN
  MERGE INTO MEGA.CCS_TB_GFIN_PARAM D
  USING (SELECT 'LIB_BAIXA_DIAS_UTEIS' CH,
                3 VL,
                'NUMERO DE DIAS UTEIS PARA BAIXA' DS
           FROM DUAL) S
  ON (D.PARAM_ST_CHAVE = S.CH)
  WHEN MATCHED THEN UPDATE SET D.PARAM_ST_DESCRICAO = S.DS
  WHEN NOT MATCHED THEN INSERT (PARAM_ST_CHAVE, PARAM_RE_VALOR, PARAM_ST_DESCRICAO)
       VALUES (S.CH, S.VL, S.DS);
  COMMIT;
END;
/

-- [23/07/2026 - ALEXANDRE CARVALHO] 2b. Parametro Mostrar IMPCREC --------------
-- 0 (padrao) = tela de Liberacao NAO exibe titulos IMPCREC; 1 = exibe.
BEGIN
  MERGE INTO MEGA.CCS_TB_GFIN_PARAM D
  USING (SELECT 'LIB_BAIXA_MOSTRA_IMPCREC' CH,
                0 VL,
                'MOSTRAR TITULOS IMPCREC NA TELA DE LIBERACAO (1=SIM/0=NAO)' DS
           FROM DUAL) S
  ON (D.PARAM_ST_CHAVE = S.CH)
  WHEN MATCHED THEN UPDATE SET D.PARAM_ST_DESCRICAO = S.DS
  WHEN NOT MATCHED THEN INSERT (PARAM_ST_CHAVE, PARAM_RE_VALOR, PARAM_ST_DESCRICAO)
       VALUES (S.CH, S.VL, S.DS);
  COMMIT;
END;
/

-- [23/07/2026 - ALEXANDRE CARVALHO] 3. Historico de alteracoes -----------------
-- Auditoria por trigger na propria CCS_TB_GFIN_PARAM: qualquer UPDATE que mude
-- PARAM_RE_VALOR (via API ou manual) gera linha no historico com de/para e o
-- usuario que a API carimbou em PARAM_IN_USU/PARAM_ST_USU.
CREATE TABLE MEGA.CCS_TB_GFIN_PARAM_HIST (
  HIST_IN_CODIGO     NUMBER        NOT NULL,
  PARAM_ST_CHAVE     VARCHAR2(50)  NOT NULL,
  HIST_RE_VALOR_ANT  NUMBER,
  HIST_RE_VALOR_NOVO NUMBER        NOT NULL,
  HIST_IN_USU        NUMBER,
  HIST_ST_USU        VARCHAR2(60),
  HIST_DT_ALTERACAO  DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CCS_TB_GFIN_PARAM_HIST PRIMARY KEY (HIST_IN_CODIGO)
);

CREATE SEQUENCE MEGA.CCS_SEQ_GFIN_PARAM_HIST START WITH 1;

CREATE OR REPLACE TRIGGER MEGA.CCS_T_GFIN_PARAM_HIST_BI
  BEFORE INSERT ON MEGA.CCS_TB_GFIN_PARAM_HIST
  FOR EACH ROW
BEGIN
  IF :NEW.HIST_IN_CODIGO IS NULL THEN
    :NEW.HIST_IN_CODIGO := MEGA.CCS_SEQ_GFIN_PARAM_HIST.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER MEGA.CCS_T_GFIN_PARAM_HIST
  AFTER UPDATE OF PARAM_RE_VALOR ON MEGA.CCS_TB_GFIN_PARAM
  FOR EACH ROW
  WHEN (NVL(OLD.PARAM_RE_VALOR,-999999) <> NVL(NEW.PARAM_RE_VALOR,-999999))
BEGIN
  INSERT INTO MEGA.CCS_TB_GFIN_PARAM_HIST
    (PARAM_ST_CHAVE, HIST_RE_VALOR_ANT, HIST_RE_VALOR_NOVO, HIST_IN_USU, HIST_ST_USU)
  VALUES
    (:NEW.PARAM_ST_CHAVE, :OLD.PARAM_RE_VALOR, :NEW.PARAM_RE_VALOR,
     :NEW.PARAM_IN_USU, :NEW.PARAM_ST_USU);
END;
/

-- [23/07/2026 - ALEXANDRE CARVALHO] 2c. Parametro Mostrar empresas do grupo ----
-- 0 (padrao) = tela de Liberacao NAO exibe titulos cujo cliente e empresa do
-- grupo (agente com TAU 'G' no GLO_AGENTES_ID: 100/200/300/400/401...); 1 = exibe.
BEGIN
  MERGE INTO MEGA.CCS_TB_GFIN_PARAM D
  USING (SELECT 'LIB_BAIXA_MOSTRA_GRUPO' CH,
                0 VL,
                'MOSTRAR TITULOS DE EMPRESAS DO GRUPO NA TELA DE LIBERACAO (1=SIM/0=NAO)' DS
           FROM DUAL) S
  ON (D.PARAM_ST_CHAVE = S.CH)
  WHEN MATCHED THEN UPDATE SET D.PARAM_ST_DESCRICAO = S.DS
  WHEN NOT MATCHED THEN INSERT (PARAM_ST_CHAVE, PARAM_RE_VALOR, PARAM_ST_DESCRICAO)
       VALUES (S.CH, S.VL, S.DS);
  COMMIT;
END;
/

-- [23/07/2026 - ALEXANDRE CARVALHO] 2d. Extensao manual do "grupo" ------------
-- Agentes que sao empresas do grupo mas nao tem TAU 'G' no cadastro (cadastros-
-- CLIENTE das proprias empresas). O filtro "Mostrar empresas do grupo" da tela
-- de Liberacao considera TAU 'G' OU presenca nesta tabela.
CREATE TABLE MEGA.CCS_TB_GFIN_LIB_GRUPO_AGN (
  AGN_IN_CODIGO     NUMBER NOT NULL,
  GRU_ST_OBSERVACAO VARCHAR2(100),
  GRU_DT_INCLUSAO   DATE DEFAULT SYSDATE,
  CONSTRAINT PK_CCS_GFIN_LIB_GRUPO_AGN PRIMARY KEY (AGN_IN_CODIGO)
);

BEGIN
  MERGE INTO MEGA.CCS_TB_GFIN_LIB_GRUPO_AGN D
  USING (SELECT 10707 AGN, 'NORMA LUCIA SOARES VIEGAS' OBS FROM DUAL
   UNION SELECT 23979, 'QUALITY IND DE ESQUADRIAS E MANGUEIRAS' FROM DUAL
   UNION SELECT 21703, 'FREEDOM IND ESQ MANG NORDESTE' FROM DUAL
   UNION SELECT 21704, 'FREEDOM IND ESQ MANG NORDESTE' FROM DUAL
   UNION SELECT 21574, 'FREEDOM IND ESQ MANG NORDESTE' FROM DUAL) S
  ON (D.AGN_IN_CODIGO = S.AGN)
  WHEN NOT MATCHED THEN INSERT (AGN_IN_CODIGO, GRU_ST_OBSERVACAO) VALUES (S.AGN, S.OBS);
  COMMIT;
END;
/
