-- [23/07/2026 - CRIADO POR ALEXANDRE CARVALHO] Liberacao de Exc./Alt. —
-- trava de alteracao/exclusao de titulo CR ja baixado (baixa total ou parcial)
-- nas filiais da INDUSTRIA (varejo 401-404/501-504 fora), liberada pontualmente
-- pela tela "Liberacao de Exc./Alt." do Gestor Financeiro.
--
-- Pecas:
--   CCS_TB_LIBERA_EXC_ALT       - liberacoes (titulo FIL+AGN+DOC+PARCELA, status A/C)
--   CCS_TB_LIBERA_EXC_ALT_EXEC  - execucoes (cada UPDATE/DELETE permitido; U/D)
--   CCS_PKG_LIBERA_EXC_ALT      - [13/08] memoria de transacao (liberacao vale por
--                                 OPERACAO, nao por vinculo BXCRE)
--   CCS_T_LIBERA_EXC_ALT        - trigger BEFORE UPDATE OF <colunas sensiveis> OR DELETE
--                                 em FIN_MOVIMENTO (ENABLED)
--
-- Regras da trigger:
--   * So age com usuario no contexto (jobs/integracoes com usuario nulo/0 passam).
--   * Varejo e PDV fora.
--   * "Titulo com baixa" = existe FIN_REFERENCIAFIN tipo BXCRE com o titulo como REF.
--     (NAO usar MOV_CH_NATUREZA: titulo CR tem natureza 'D' — semantica contabil.)
--   * DELETE de linha de baixa (TPD 'CREDITO' + CONT_TAC BXCRE/MVFIN/MVCRE) tambem
--     exige liberacao (estorno de baixa). UPDATE em linha de baixa nao trava (o
--     estorno legitimo atualiza saldo do titulo em colunas fora da lista sensivel).
--   * Pegadinha: DELETING/UPDATING nao podem ser usados DENTRO de SQL — guardar
--     em variavel antes (ORA-00920 se usar direto no INSERT).

CREATE TABLE MEGA.CCS_TB_LIBERA_EXC_ALT (
  LIB_IN_CODIGO       NUMBER        NOT NULL,
  FIL_IN_CODIGO       NUMBER        NOT NULL,
  AGN_IN_CODIGO       NUMBER        NOT NULL,
  LIB_ST_DOCUMENTO    VARCHAR2(20)  NOT NULL,
  LIB_ST_PARCELA      VARCHAR2(6),
  LIB_ST_MOTIVO       VARCHAR2(200),
  LIB_CH_STATUS       VARCHAR2(1)   DEFAULT 'A' NOT NULL,
  LIB_IN_USU_LIBEROU  NUMBER,
  LIB_ST_USU_LIBEROU  VARCHAR2(60),
  LIB_DT_LIBERACAO    DATE          DEFAULT SYSDATE NOT NULL,
  LIB_IN_USU_CANCELOU NUMBER,
  LIB_DT_CANCELAMENTO DATE,
  CONSTRAINT PK_CCS_TB_LIBERA_EXC_ALT PRIMARY KEY (LIB_IN_CODIGO),
  CONSTRAINT CK_CCS_LIBERA_EXALT_ST CHECK (LIB_CH_STATUS IN ('A','E','C'))
);

CREATE TABLE MEGA.CCS_TB_LIBERA_EXC_ALT_EXEC (
  LIBE_IN_CODIGO       NUMBER      NOT NULL,
  LIB_IN_CODIGO        NUMBER      NOT NULL,
  LIBE_CH_OPERACAO     VARCHAR2(1) NOT NULL,
  MOV_TAB_IN_CODIGO    NUMBER,
  MOV_SEQ_IN_CODIGO    NUMBER,
  MOV_IN_NUMLANCTO     NUMBER,
  LIBE_IN_USU_EXECUTOU NUMBER,
  LIBE_DT_EXECUCAO     DATE        DEFAULT SYSDATE NOT NULL,
  LIBE_RE_VALOR        NUMBER,
  CONSTRAINT PK_CCS_TB_LIBERA_EXALT_EXEC PRIMARY KEY (LIBE_IN_CODIGO),
  CONSTRAINT CK_CCS_LIBERA_EXALT_OP CHECK (LIBE_CH_OPERACAO IN ('U','D'))
);

CREATE SEQUENCE MEGA.CCS_SEQ_LIBERA_EXC_ALT START WITH 1;
CREATE SEQUENCE MEGA.CCS_SEQ_LIBERA_EXALT_EXEC START WITH 1;

-- [23/07/2026 - ALEXANDRE CARVALHO] V4: gate do ESTORNO no DELETE do
-- vinculo BXCRE (FIN_REFERENCIAFIN) — primeiro passo obrigatorio do estorno
-- (3 FKs impedem apagar o movimento antes). Trigger do movimento cuida so do
-- TITULO. Adiantamentos (ADCLI/CREDITO MVFIN) e transferencias LIVRES.
-- Historico: V1 gate por TPD/CONT_TAC (pegou adiantamento indevidamente);
-- V2 uso unico; V3 tentativa por ORI_* (colunas erradas — o vinculo usa MOV_*).
-- [24/07/2026 - ALEXANDRE CARVALHO] V5 (trigger do movimento): baixa nova em
-- titulo (parcialmente) baixado passa sem liberacao — so mexe no acumulado
-- MOV_RE_VALORCRE; alteracao estrutural/DELETE/estorno seguem gateados.
-- [13/08/2026 - ALEXANDRE CARVALHO] V6 (trigger _REF): a liberacao vale para a
-- OPERACAO inteira, nao por vinculo. Baixa com juros/desconto gera 2+ vinculos
-- BXCRE do mesmo titulo (caso DEPR 19566090: CREDITO 1338,04 do NFCR + CREDITO
-- 0,11 do DEBITO de juros, ambos 16701-003 AGN 25051 FIL 700) e a V4 exigia uma
-- liberacao por vinculo — impossivel, a API bloqueia 2a liberacao ativa do mesmo
-- titulo (409 ja_liberado). Agora o 1o vinculo consome a liberacao (A->E) e
-- registra na memoria de transacao (CCS_PKG_LIBERA_EXC_ALT); os demais vinculos
-- do MESMO titulo na MESMA transacao passam gravando execucao na mesma LIB.
-- Rollback invalida a memoria (o id da transacao muda junto com o UPDATE desfeito).

CREATE OR REPLACE TRIGGER MEGA.CCS_T_LIBERA_EXC_ALT
  BEFORE UPDATE OF MOV_RE_VALOR, MOV_RE_VALORCRE, MOV_DT_DATADOCTO, MOV_DT_VENCTO,
                   MOV_DT_PRORROGADO, MOV_ST_DOCUMENTO, MOV_ST_PARCELA, AGN_IN_CODIGO
      OR DELETE
  ON MEGA.FIN_MOVIMENTO
  FOR EACH ROW
DECLARE
  -- [23/07/2026 - ALEXANDRE CARVALHO] V4: ESTA TRIGGER CUIDA SO DO TITULO CR BAIXADO
  -- (LINHA QUE E REF DE VINCULO BXCRE NA FIN_REFERENCIAFIN): UPDATE SENSIVEL OU DELETE
  -- EXIGEM LIBERACAO (USO UNICO, A->E). O ESTORNO DA BAIXA E GATEADO NA TRIGGER IRMA
  -- CCS_T_LIBERA_EXC_ALT_REF (DELETE DO VINCULO BXCRE - PRIMEIRO PASSO OBRIGATORIO DO
  -- ESTORNO POR CAUSA DAS FKS). ADIANTAMENTO/TRANSFERENCIA/OUTRAS LINHAS: LIVRES AQUI.
  -- REGRAS: INDUSTRIA (VAREJO 401-404/501-504 FORA), PDV FORA, SEM USUARIO NO CONTEXTO
  -- PASSA. NUNCA USAR MOV_CH_NATUREZA (TITULO CR E 'D').
  wUSUARIO  NUMBER;
  vLIB      NUMBER;
  vTEM      NUMBER;
  vOPER     VARCHAR2(1);
BEGIN
  wUSUARIO := TO_NUMBER(MEGA.GLO_PCK_CONTEXTO.F_GETVARIAVEL('vUSU_IN_CODIGO'));
  IF wUSUARIO IS NULL OR wUSUARIO = 0 THEN RETURN; END IF;
  IF DELETING THEN vOPER := 'D'; ELSE vOPER := 'U'; END IF;
  IF :OLD.FIL_IN_CODIGO IN (401,402,403,404,501,502,503,504) THEN RETURN; END IF;
  IF :OLD.TPD_ST_CODIGO = 'PDV' THEN RETURN; END IF;

  -- [24/07/2026 - ALEXANDRE CARVALHO] V5: BAIXA NOVA EM TITULO (PARCIALMENTE) BAIXADO PASSA SEM LIBERACAO:
  -- A BAIXA SO MEXE NO ACUMULADO DE CREDITO (MOV_RE_VALORCRE). SE OS CAMPOS ESTRUTURAIS
  -- (VALOR, DATAS, DOCUMENTO, PARCELA, AGENTE) NAO MUDARAM, NAO E ALTERACAO DE TITULO.
  -- ALTERACAO ESTRUTURAL, DELETE E ESTORNO (TRIGGER IRMA _REF) SEGUEM EXIGINDO LIBERACAO.
  IF UPDATING THEN
    IF NVL(:NEW.MOV_RE_VALOR,0) = NVL(:OLD.MOV_RE_VALOR,0)
       AND NVL(:NEW.MOV_DT_DATADOCTO, TO_DATE('01/01/1900','DD/MM/YYYY')) = NVL(:OLD.MOV_DT_DATADOCTO, TO_DATE('01/01/1900','DD/MM/YYYY'))
       AND NVL(:NEW.MOV_DT_VENCTO,    TO_DATE('01/01/1900','DD/MM/YYYY')) = NVL(:OLD.MOV_DT_VENCTO,    TO_DATE('01/01/1900','DD/MM/YYYY'))
       AND NVL(:NEW.MOV_DT_PRORROGADO,TO_DATE('01/01/1900','DD/MM/YYYY')) = NVL(:OLD.MOV_DT_PRORROGADO,TO_DATE('01/01/1900','DD/MM/YYYY'))
       AND NVL(:NEW.MOV_ST_DOCUMENTO,'#') = NVL(:OLD.MOV_ST_DOCUMENTO,'#')
       AND NVL(:NEW.MOV_ST_PARCELA,'#')   = NVL(:OLD.MOV_ST_PARCELA,'#')
       AND NVL(:NEW.AGN_IN_CODIGO,0)      = NVL(:OLD.AGN_IN_CODIGO,0)
    THEN
      RETURN;
    END IF;
  END IF;

  SELECT COUNT(*) INTO vTEM
    FROM MEGA.FIN_REFERENCIAFIN R
   WHERE R.REF_MOV_TAB_IN_CODIGO = :OLD.MOV_TAB_IN_CODIGO
     AND R.REF_MOV_SEQ_IN_CODIGO = :OLD.MOV_SEQ_IN_CODIGO
     AND R.REF_MOV_IN_NUMLANCTO  = :OLD.MOV_IN_NUMLANCTO
     AND R.REF_ST_TIPO           = 'BXCRE'
     AND ROWNUM = 1;
  IF vTEM = 0 THEN RETURN; END IF;

  UPDATE MEGA.CCS_TB_LIBERA_EXC_ALT L
     SET L.LIB_CH_STATUS = 'E'
   WHERE L.LIB_IN_CODIGO = (SELECT MIN(X.LIB_IN_CODIGO)
                              FROM MEGA.CCS_TB_LIBERA_EXC_ALT X
                             WHERE X.AGN_IN_CODIGO    = :OLD.AGN_IN_CODIGO
                               AND X.LIB_ST_DOCUMENTO = :OLD.MOV_ST_DOCUMENTO
                               AND X.FIL_IN_CODIGO    = :OLD.FIL_IN_CODIGO
                               AND (X.LIB_ST_PARCELA IS NULL OR X.LIB_ST_PARCELA = :OLD.MOV_ST_PARCELA)
                               AND X.LIB_CH_STATUS    = 'A')
     AND L.LIB_CH_STATUS = 'A'
  RETURNING L.LIB_IN_CODIGO INTO vLIB;

  IF SQL%ROWCOUNT = 1 THEN
    INSERT INTO MEGA.CCS_TB_LIBERA_EXC_ALT_EXEC
      (LIBE_IN_CODIGO, LIB_IN_CODIGO, LIBE_CH_OPERACAO, MOV_TAB_IN_CODIGO,
       MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO, LIBE_IN_USU_EXECUTOU, LIBE_DT_EXECUCAO, LIBE_RE_VALOR)
    VALUES
      (MEGA.CCS_SEQ_LIBERA_EXALT_EXEC.NEXTVAL, vLIB, vOPER,
       :OLD.MOV_TAB_IN_CODIGO, :OLD.MOV_SEQ_IN_CODIGO, :OLD.MOV_IN_NUMLANCTO,
       wUSUARIO, SYSDATE, NVL(:OLD.MOV_RE_VALORCRE, :OLD.MOV_RE_VALOR));
  ELSE
    RAISE_APPLICATION_ERROR(-20001, 'USUARIO ('|| wUSUARIO ||') NAO POSSUI AUTORIZACAO PARA '
      || CASE WHEN vOPER = 'D' THEN 'EXCLUIR' ELSE 'ALTERAR' END
      || ' TITULO JA BAIXADO! A LIBERACAO E DE USO UNICO - SOLICITE UMA NOVA NA TELA LIBERACAO DE EXC/ALT DO GESTOR FINANCEIRO.');
  END IF;
END;
/

-- [13/08/2026 - ALEXANDRE CARVALHO] MEMORIA DE TRANSACAO DA LIBERACAO DE EXC/ALT
CREATE OR REPLACE PACKAGE MEGA.CCS_PKG_LIBERA_EXC_ALT AS
  -- [13/08/2026 - ALEXANDRE CARVALHO] MEMORIA DE TRANSACAO DA LIBERACAO DE EXC/ALT:
  -- UMA LIBERACAO VALE PARA A OPERACAO (TRANSACAO) INTEIRA SOBRE O TITULO, NAO POR
  -- VINCULO BXCRE. BAIXA COM JUROS/DESCONTO GERA 2+ VINCULOS DO MESMO TITULO E A
  -- TRIGGER CCS_T_LIBERA_EXC_ALT_REF DISPARA UMA VEZ POR VINCULO - SEM ESTA MEMORIA
  -- O SEGUNDO DISPARO NAO ACHAVA LIBERACAO ATIVA E O ESTORNO ERA IMPOSSIVEL (CASO
  -- DEPR 19566090 / TITULO 16701-003 AGN 25051 FIL 700 EM 13/08/2026).
  -- O MAPA E LIMPO QUANDO A TRANSACAO MUDA (DBMS_TRANSACTION.LOCAL_TRANSACTION_ID),
  -- ENTAO ROLLBACK INVALIDA O CONSUMO REGISTRADO (COERENTE: O UPDATE A->E TAMBEM VOLTA).
  FUNCTION F_LIB_DA_TRANSACAO(pFIL NUMBER, pAGN NUMBER, pDOC VARCHAR2, pPARC VARCHAR2) RETURN NUMBER;
  PROCEDURE P_REGISTRA_CONSUMO(pFIL NUMBER, pAGN NUMBER, pDOC VARCHAR2, pPARC VARCHAR2, pLIB NUMBER);
END CCS_PKG_LIBERA_EXC_ALT;
/

CREATE OR REPLACE PACKAGE BODY MEGA.CCS_PKG_LIBERA_EXC_ALT AS
  -- [13/08/2026 - ALEXANDRE CARVALHO] ESTADO DE SESSAO: MAPA TITULO->LIB CONSUMIDA +
  -- ID DA TRANSACAO DONA DO MAPA. TRANSACAO NOVA (OU POS COMMIT/ROLLBACK) ZERA O MAPA.
  TYPE T_MAP IS TABLE OF NUMBER INDEX BY VARCHAR2(120);
  vMAP T_MAP;
  vTXN VARCHAR2(100) := '#NENHUMA#';

  FUNCTION F_CHAVE(pFIL NUMBER, pAGN NUMBER, pDOC VARCHAR2, pPARC VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN TO_CHAR(pFIL) || '|' || TO_CHAR(pAGN) || '|' || pDOC || '|' || NVL(pPARC, '~');
  END F_CHAVE;

  PROCEDURE P_SINCRONIZA_TXN IS
    vATUAL VARCHAR2(100);
  BEGIN
    vATUAL := NVL(DBMS_TRANSACTION.LOCAL_TRANSACTION_ID, '#NULA#');
    IF vATUAL <> vTXN THEN
      vMAP.DELETE;
      vTXN := vATUAL;
    END IF;
  END P_SINCRONIZA_TXN;

  FUNCTION F_LIB_DA_TRANSACAO(pFIL NUMBER, pAGN NUMBER, pDOC VARCHAR2, pPARC VARCHAR2) RETURN NUMBER IS
    vK VARCHAR2(120);
  BEGIN
    P_SINCRONIZA_TXN;
    vK := F_CHAVE(pFIL, pAGN, pDOC, pPARC);
    IF vMAP.EXISTS(vK) THEN
      RETURN vMAP(vK);
    END IF;
    RETURN NULL;
  END F_LIB_DA_TRANSACAO;

  PROCEDURE P_REGISTRA_CONSUMO(pFIL NUMBER, pAGN NUMBER, pDOC VARCHAR2, pPARC VARCHAR2, pLIB NUMBER) IS
  BEGIN
    P_SINCRONIZA_TXN;
    vMAP(F_CHAVE(pFIL, pAGN, pDOC, pPARC)) := pLIB;
  END P_REGISTRA_CONSUMO;
END CCS_PKG_LIBERA_EXC_ALT;
/

CREATE OR REPLACE TRIGGER MEGA.CCS_T_LIBERA_EXC_ALT_REF
  BEFORE DELETE ON MEGA.FIN_REFERENCIAFIN
  FOR EACH ROW
  WHEN (OLD.REF_ST_TIPO = 'BXCRE')
DECLARE
  -- [23/07/2026 - ALEXANDRE CARVALHO] GATE DO ESTORNO DE BAIXA DE CREDITO (EXC/ALT).
  -- APAGAR O VINCULO BXCRE E O PRIMEIRO PASSO OBRIGATORIO DO ESTORNO (FKS IMPEDEM
  -- APAGAR O MOVIMENTO ANTES). RESOLVE O TITULO (REF_MOV_*), APLICA OS SKIPS
  -- (VAREJO/PDV/SEM USUARIO) E CONSOME A LIBERACAO DE USO UNICO (A->E) REGISTRANDO
  -- EXECUCAO 'D' COM O LANCAMENTO DA BAIXA (MOV_*). SEM LIBERACAO -> ORA-20001.
  -- [13/08/2026 - ALEXANDRE CARVALHO] V6: A LIBERACAO VALE PARA A OPERACAO INTEIRA,
  -- NAO POR VINCULO. BAIXA COM JUROS/DESCONTO GERA 2+ VINCULOS BXCRE DO MESMO TITULO
  -- (CASO DEPR 19566090: CREDITO 1338,04 DO NFCR + CREDITO 0,11 DO DEBITO DE JUROS,
  -- AMBOS 16701-003 AGN 25051) E A V4 EXIGIA UMA LIBERACAO POR VINCULO - IMPOSSIVEL,
  -- A TELA SO PERMITE UMA ATIVA POR TITULO. AGORA O 1o VINCULO CONSOME A LIBERACAO E
  -- REGISTRA NA MEMORIA DE TRANSACAO (CCS_PKG_LIBERA_EXC_ALT); OS DEMAIS VINCULOS DO
  -- MESMO TITULO NA MESMA TRANSACAO PASSAM GRAVANDO EXECUCAO NA MESMA LIB.
  wUSUARIO NUMBER;
  vLIB     NUMBER;
  vFIL     NUMBER;
  vAGN     NUMBER;
  vDOC     MEGA.FIN_MOVIMENTO.MOV_ST_DOCUMENTO%TYPE;
  vPARC    MEGA.FIN_MOVIMENTO.MOV_ST_PARCELA%TYPE;
  vTPD     MEGA.FIN_MOVIMENTO.TPD_ST_CODIGO%TYPE;
  vVALOR   NUMBER;
BEGIN
  wUSUARIO := TO_NUMBER(MEGA.GLO_PCK_CONTEXTO.F_GETVARIAVEL('vUSU_IN_CODIGO'));
  IF wUSUARIO IS NULL OR wUSUARIO = 0 THEN RETURN; END IF;

  BEGIN
    SELECT M.FIL_IN_CODIGO, M.AGN_IN_CODIGO, M.MOV_ST_DOCUMENTO, M.MOV_ST_PARCELA, M.TPD_ST_CODIGO
      INTO vFIL, vAGN, vDOC, vPARC, vTPD
      FROM MEGA.FIN_MOVIMENTO M
     WHERE M.MOV_TAB_IN_CODIGO = :OLD.REF_MOV_TAB_IN_CODIGO
       AND M.MOV_SEQ_IN_CODIGO = :OLD.REF_MOV_SEQ_IN_CODIGO
       AND M.MOV_IN_NUMLANCTO  = :OLD.REF_MOV_IN_NUMLANCTO;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN;
  END;
  IF vFIL IN (401,402,403,404,501,502,503,504) THEN RETURN; END IF;
  IF vTPD = 'PDV' THEN RETURN; END IF;

  BEGIN
    SELECT M.MOV_RE_VALOR INTO vVALOR
      FROM MEGA.FIN_MOVIMENTO M
     WHERE M.MOV_TAB_IN_CODIGO = :OLD.MOV_TAB_IN_CODIGO
       AND M.MOV_SEQ_IN_CODIGO = :OLD.MOV_SEQ_IN_CODIGO
       AND M.MOV_IN_NUMLANCTO  = :OLD.MOV_IN_NUMLANCTO;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN vVALOR := NULL;
  END;

  -- [13/08/2026 - ALEXANDRE CARVALHO] V6: TITULO JA AUTORIZADO NESTA TRANSACAO?
  vLIB := MEGA.CCS_PKG_LIBERA_EXC_ALT.F_LIB_DA_TRANSACAO(vFIL, vAGN, vDOC, vPARC);
  IF vLIB IS NOT NULL THEN
    INSERT INTO MEGA.CCS_TB_LIBERA_EXC_ALT_EXEC
      (LIBE_IN_CODIGO, LIB_IN_CODIGO, LIBE_CH_OPERACAO, MOV_TAB_IN_CODIGO,
       MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO, LIBE_IN_USU_EXECUTOU, LIBE_DT_EXECUCAO, LIBE_RE_VALOR)
    VALUES
      (MEGA.CCS_SEQ_LIBERA_EXALT_EXEC.NEXTVAL, vLIB, 'D',
       :OLD.MOV_TAB_IN_CODIGO, :OLD.MOV_SEQ_IN_CODIGO, :OLD.MOV_IN_NUMLANCTO,
       wUSUARIO, SYSDATE, vVALOR);
    RETURN;
  END IF;

  UPDATE MEGA.CCS_TB_LIBERA_EXC_ALT L
     SET L.LIB_CH_STATUS = 'E'
   WHERE L.LIB_IN_CODIGO = (SELECT MIN(X.LIB_IN_CODIGO)
                              FROM MEGA.CCS_TB_LIBERA_EXC_ALT X
                             WHERE X.AGN_IN_CODIGO    = vAGN
                               AND X.LIB_ST_DOCUMENTO = vDOC
                               AND X.FIL_IN_CODIGO    = vFIL
                               AND (X.LIB_ST_PARCELA IS NULL OR X.LIB_ST_PARCELA = vPARC)
                               AND X.LIB_CH_STATUS    = 'A')
     AND L.LIB_CH_STATUS = 'A'
  RETURNING L.LIB_IN_CODIGO INTO vLIB;

  IF SQL%ROWCOUNT = 1 THEN
    INSERT INTO MEGA.CCS_TB_LIBERA_EXC_ALT_EXEC
      (LIBE_IN_CODIGO, LIB_IN_CODIGO, LIBE_CH_OPERACAO, MOV_TAB_IN_CODIGO,
       MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO, LIBE_IN_USU_EXECUTOU, LIBE_DT_EXECUCAO, LIBE_RE_VALOR)
    VALUES
      (MEGA.CCS_SEQ_LIBERA_EXALT_EXEC.NEXTVAL, vLIB, 'D',
       :OLD.MOV_TAB_IN_CODIGO, :OLD.MOV_SEQ_IN_CODIGO, :OLD.MOV_IN_NUMLANCTO,
       wUSUARIO, SYSDATE, vVALOR);
    MEGA.CCS_PKG_LIBERA_EXC_ALT.P_REGISTRA_CONSUMO(vFIL, vAGN, vDOC, vPARC, vLIB);
  ELSE
    RAISE_APPLICATION_ERROR(-20001, 'USUARIO ('|| wUSUARIO ||') NAO POSSUI AUTORIZACAO PARA EXCLUIR/ESTORNAR BAIXA DE TITULO! A LIBERACAO E DE USO UNICO - SOLICITE UMA NOVA NA TELA LIBERACAO DE EXC/ALT DO GESTOR FINANCEIRO.');
  END IF;
END;
/
