-- [06/08/2026 - CRIADO POR ALEXANDRE CARVALHO] MODULO "LIBERACAO DE AGENTES" DO GESTOR FINANCEIRO.
-- A LIBERACAO MANUAL DO BLOQUEIO POR ATRASO (GLO_AGENTESCMPESP.AGN_BO_BLOQUEIO), QUE ERA FEITA
-- NO CAMPO ESPECIFICO DO CADASTRO DO AGENTE NO MEGA XT, PASSA A SER FEITA PELA TELA
-- "LIBERACAO DE AGENTES" DO PORTAL (MENU LIBERACAO), COM CONTROLE DE ACESSO POR MODULO E LOG
-- DE QUEM LIBEROU/REVOGOU. O MOTOR NAO MUDA: CCS_P_BLOQUEIA_CLIENTE / _RESERVA CONTINUAM
-- LENDO A FLAG, E O JOB CCS_JOB_RESET_BLOQ_CLI (03:00) CONTINUA ZERANDO DIARIAMENTE.
-- O CONTROLE VISUAL DO CAMPO FOI REMOVIDO DO FORM CEFOGLO_AGENTESCMPESP (901024) EM 06/08/2026.

-- LOG DE LIBERACOES/REVOGACOES
CREATE TABLE MEGA.CCS_TB_GFIN_LIBERA_AGN_LOG (
  LOG_IN_CODIGO   NUMBER       NOT NULL,
  AGN_IN_CODIGO   NUMBER       NOT NULL,
  LOG_CH_DE       VARCHAR2(1),               -- VALOR ANTERIOR DA FLAG (S/N)
  LOG_CH_PARA     VARCHAR2(1)  NOT NULL,     -- VALOR NOVO (S = LIBEROU / N = REVOGOU)
  LOG_ST_MOTIVO   VARCHAR2(200),
  LOG_IN_USU      NUMBER,                    -- USUARIO MEGA (GRU_IN_CODIGO)
  LOG_ST_USU      VARCHAR2(60),              -- LOGIN
  LOG_DT_DATA     DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT CCS_PK_GFIN_LIBERA_AGN_LOG PRIMARY KEY (LOG_IN_CODIGO)
);

CREATE SEQUENCE MEGA.CCS_SEQ_GFIN_LIBERA_AGN_LOG START WITH 1;

CREATE INDEX MEGA.CCS_IX_GFIN_LIBAGN_AGN
  ON MEGA.CCS_TB_GFIN_LIBERA_AGN_LOG (AGN_IN_CODIGO, LOG_DT_DATA);

-- MODULO NO CATALOGO (ASCII PURO - DEPLOY SOAP CORROMPE ACENTO)
MERGE INTO MEGA.CCS_TB_GFIN_MODULO M
USING (SELECT 'LIBERACAO_AGENTES' COD FROM DUAL) X
   ON (M.MOD_ST_CODIGO = X.COD)
 WHEN NOT MATCHED THEN
      INSERT (MOD_ST_CODIGO, MOD_ST_NOME, MOD_IN_ORDEM, MOD_CH_ATIVO)
      VALUES ('LIBERACAO_AGENTES', 'Liberacao de Agentes', 7, 'S');
COMMIT;
