-- [09/09/2026 - Alexandre Carvalho] Trava de baixa retroativa (V7 vigente) - espelho do fonte vivo
-- em producao OCPDB493. V7: a janela de N dias uteis passa a ser calculada pela funcao nova
-- MEGA.CCS_F_ANTDIAUTIL_N (abaixo, criada antes da trigger), independente do NLS da sessao. A nativa
-- F_ANTDIAUTIL, em sessao portuguesa, avanca para a sexta seguinte quando o feriado cai na segunda
-- (07/09/2026) e o laco antigo ciclava entre 08 e 11/09 bloqueando toda baixa com data anterior ao dia.
-- Backup da V6 em CCS_TB_BKP_TRG_DTBAIXA_09092026. Historico: V1-V5 so em backups CTAS; V6 em 13/08/2026.

CREATE OR REPLACE FUNCTION      CCS_F_ANTDIAUTIL_N
(PDATA IN DATE, PDIAS IN NUMBER, PAGN_PAD_IN_CODIGO IN NUMBER, PAGN_IN_CODIGO IN NUMBER)
RETURN DATE IS
-- [09/09/2026 - ALEXANDRE CARVALHO] CRIADO: DEVOLVE A DATA N DIAS UTEIS ANTES DE PDATA (PDATA NAO CONTA),
-- PULANDO SABADO/DOMINGO E FERIADOS DA GLO_FERIADO (F NACIONAL; E ESTADUAL PELA UF DO AGENTE; R MUNICIPAL
-- PELA UF+MUNICIPIO DO AGENTE). SUBSTITUI O ENCADEAMENTO DE F_ANTDIAUTIL NA CCS_T_DATA_BAIXA: A NATIVA,
-- EM SESSAO COM NLS PORTUGUES, CAI NO RAMO NEXT_DAY(VDATA,'SEXTA') SEM O -4 QUANDO O FERIADO CAI NA SEGUNDA
-- (07/09/2026) E AVANCA PARA A SEXTA SEGUINTE - O LACO DA TRIGGER CICLAVA ENTRE 08 E 11/09 E BLOQUEAVA
-- TODAS AS BAIXAS. DIA DA SEMANA POR TRUNC(D,'IW') (INDEPENDE DE NLS). GUARDA DE 3000 ITERACOES.
  VDATA DATE := TRUNC(PDATA);
  VN    NUMBER := 0;
  VFER  NUMBER;
  VUF   VARCHAR2(2);
  VMUN  NUMBER;
  VDOW  NUMBER;
  VITER NUMBER := 0;
BEGIN
  IF NVL(PDIAS, 0) <= 0 THEN
    RETURN VDATA;
  END IF;
  BEGIN
    SELECT A.UF_ST_SIGLA, A.MUN_IN_CODIGO
      INTO VUF, VMUN
      FROM MEGA.GLO_AGENTES A
     WHERE A.AGN_TAB_IN_CODIGO = 53
       AND A.AGN_PAD_IN_CODIGO = PAGN_PAD_IN_CODIGO
       AND A.AGN_IN_CODIGO     = PAGN_IN_CODIGO
       AND ROWNUM = 1;
  EXCEPTION
    WHEN OTHERS THEN
      VUF := NULL; VMUN := NULL;
  END;
  WHILE VN < PDIAS LOOP
    VDATA := VDATA - 1;
    VITER := VITER + 1;
    IF VITER > 3000 THEN
      RETURN VDATA;
    END IF;
    VDOW := VDATA - TRUNC(VDATA, 'IW'); -- 0=SEGUNDA ... 5=SABADO, 6=DOMINGO
    IF VDOW NOT IN (5, 6) THEN
      SELECT COUNT(*)
        INTO VFER
        FROM MEGA.GLO_FERIADO F
       WHERE TRUNC(F.FER_DT_FERIADO) = VDATA
         AND (F.FER_CH_TIPO = 'F'
              OR (F.FER_CH_TIPO = 'E' AND F.UF_ST_SIGLA = VUF)
              OR (F.FER_CH_TIPO = 'R' AND F.UF_ST_SIGLA = VUF AND F.MUN_IN_CODIGO = VMUN));
      IF VFER = 0 THEN
        VN := VN + 1;
      END IF;
    END IF;
  END LOOP;
  RETURN VDATA;
END;
/

CREATE OR REPLACE TRIGGER MEGA.CCS_T_DATA_BAIXA
  BEFORE INSERT ON MEGA.FIN_MOVIMENTO
FOR EACH ROW
DECLARE
    wUSUARIO     NUMBER;
    vLIB         NUMBER;
    vLIMITE      DATE;
    vDIAS        NUMBER;
    vRECEB       BOOLEAN := FALSE;
BEGIN
   -- VERIFICA O USUARIO QUE ESTA LOGADO NO CONTEXTO.
   wUSUARIO := TO_NUMBER(MEGA.GLO_PCK_CONTEXTO.F_GETVARIAVEL('vUSU_IN_CODIGO'));
 -- [23/07/2026 - ALEXANDRE CARVALHO] V5:
 --  * JANELA DE DIAS UTEIS AGORA VEM DO PARAMETRO LIB_BAIXA_DIAS_UTEIS (MEGA.CCS_TB_GFIN_PARAM,
 --    TELA PARAMETROS DA LIBERACAO DE DATA DE BAIXA DO GESTOR FINANCEIRO). FALLBACK = 3.
 --  * FLAG GRU_ST_BAIXA_DATAANT REMOVIDA DA REGRA - TODOS OBEDECEM A MESMA REGRA NA INDUSTRIA.
 --  * FILIAIS DE VAREJO (401,402,403,404,501,502,503,504) FORA DA REGRA.
 --  * MANTIDO: LIBERACAO PONTUAL TITULO+DATA (CCS_TB_LIBERA_DATA_BAIXA 'A' + EXEC),
 --    LOG FIN_MOVIMENTO_BAIXA_LOG, BYPASS DE PROCESSOS SEM USUARIO NO CONTEXTO (NULO/0).
 --  * BACKUPS: CCS_TB_BKP_TRG_DTBAIXA_10072026 (ORIGINAL) / _V3_10072026 (V3) / _23072026 (V4).
 -- [13/08/2026 - ALEXANDRE CARVALHO] V6: ENTRADA DE DEVOLUCAO DE CLIENTE (ACAO 327, TPD ADCLI)
 --  NAO PODE SER TRAVADA - O RECEBIMENTO BAIXA O TITULO ORIGINAL COM A DATA ANTIGA DELE E O
 --  OPERADOR NAO TEM COMO ESCOLHER OUTRA DATA. AS LINHAS FINANCEIRAS DA DEVOLUCAO NAO CARREGAM
 --  A ACAO 327 (CARREGAM 704/715 DO FINANCEIRO), ENTAO O GATE E PELA PILHA DE CHAMADAS:
 --  INSERT VINDO DE MEGA.P_PROCESSOPENDENTERECEBIMENTO (MOTOR DO RECEBIMENTO) PASSA SEM TRAVA,
 --  MAS AINDA GRAVA O LOG FIN_MOVIMENTO_BAIXA_LOG (AUDITORIA). BAIXA MANUAL SEGUE TRAVADA.
 --  BACKUP DA V5: CCS_TB_BKP_TRG_DTBAIXA_13082026.
-- [09/09/2026 - ALEXANDRE CARVALHO] V7: JANELA DE DIAS UTEIS PELA CCS_F_ANTDIAUTIL_N (VER COMENTARIO NO CORPO).
 IF (:NEW.CONT_TAC_ST_CODIGO IN ('BXCRE','MVFIN','MVCRE'))
    AND :NEW.TPD_ST_CODIGO IN ('CREDITO')
    AND (:NEW.MOV_DT_DATADOCTO < TRUNC(SYSDATE))
    AND :NEW.FIL_IN_CODIGO NOT IN (401,402,403,404,501,502,503,504) THEN
   BEGIN
         INSERT INTO MEGA.FIN_MOVIMENTO_BAIXA_LOG
         (ORG_TAB_IN_CODIGO,   ORG_PAD_IN_CODIGO,       ORG_IN_CODIGO,         ORG_TAU_ST_CODIGO,
          MOV_TAB_IN_CODIGO,   MOV_SEQ_IN_CODIGO,       MOV_IN_NUMLANCTO,      CONT_TAB_IN_CODIGO,
          CONT_PAD_IN_CODIGO,  CONT_TAC_ST_CODIGO,      CONT_CON_IN_SEQUENCIA, DATA,
          USU_IN_CODIGO)
          VALUES
          (:NEW.ORG_TAB_IN_CODIGO,   :NEW.ORG_PAD_IN_CODIGO,       :NEW.ORG_IN_CODIGO,         :NEW.ORG_TAU_ST_CODIGO,
           :NEW.MOV_TAB_IN_CODIGO,   :NEW.MOV_SEQ_IN_CODIGO,       :NEW.MOV_IN_NUMLANCTO,      :NEW.CONT_TAB_IN_CODIGO,
           :NEW.CONT_PAD_IN_CODIGO,  :NEW.CONT_TAC_ST_CODIGO,      :NEW.CONT_CON_IN_SEQUENCIA,  SYSDATE,
           wUSUARIO);
   END;
   -- [13/08/2026 - ALEXANDRE CARVALHO] V6: FLUXO DE RECEBIMENTO (DEVOLUCAO DE CLIENTE) PASSA.
   FOR I IN 1..UTL_CALL_STACK.DYNAMIC_DEPTH LOOP
     IF INSTR(UPPER(UTL_CALL_STACK.CONCATENATE_SUBPROGRAM(UTL_CALL_STACK.SUBPROGRAM(I))),
              'P_PROCESSOPENDENTERECEBIMENTO') > 0 THEN
       vRECEB := TRUE;
       EXIT;
     END IF;
   END LOOP;
   IF vRECEB THEN
     RETURN;
   END IF;
   -- JANELA LIVRE DE N DIAS UTEIS PARA TRAS (N = PARAMETRO; F_ANTDIAUTIL DEVOLVE A PROPRIA
   -- DATA SE JA FOR UTIL, POR ISSO O ENCADEAMENTO SOBRE DATA-1 A CADA PASSO).
   BEGIN
     SELECT GREATEST(TRUNC(PARAM_RE_VALOR), 0)
       INTO vDIAS
       FROM MEGA.CCS_TB_GFIN_PARAM
      WHERE PARAM_ST_CHAVE = 'LIB_BAIXA_DIAS_UTEIS';
   EXCEPTION
     WHEN NO_DATA_FOUND THEN vDIAS := 3;
   END;
   -- [09/09/2026 - ALEXANDRE CARVALHO] V7: LIMITE CALCULADO PELA CCS_F_ANTDIAUTIL_N (N DIAS UTEIS PARA TRAS,
   --  INDEPENDENTE DE NLS). O ENCADEAMENTO DA NATIVA F_ANTDIAUTIL CICLAVA ENTRE 08 E 11/09/2026 QUANDO O
   --  FERIADO CAIA NA SEGUNDA (07/09) - EM SESSAO PORTUGUESA ELA AVANCA PARA A SEXTA SEGUINTE - E TODA
   --  BAIXA COM DATA ANTERIOR AO DIA CORRENTE ERA BLOQUEADA. BACKUP DA V6: CCS_TB_BKP_TRG_DTBAIXA_09092026.
   vLIMITE := MEGA.CCS_F_ANTDIAUTIL_N(TRUNC(SYSDATE), vDIAS, :NEW.AGN_PAD_IN_CODIGO, :NEW.AGN_IN_CODIGO);
   IF (TRUNC(:NEW.MOV_DT_DATADOCTO) < vLIMITE) AND wUSUARIO IS NOT NULL AND wUSUARIO <> 0 THEN
        BEGIN
          SELECT L.LIB_IN_CODIGO
            INTO vLIB
            FROM MEGA.CCS_TB_LIBERA_DATA_BAIXA L
           WHERE L.AGN_IN_CODIGO    = :NEW.AGN_IN_CODIGO
             AND L.LIB_ST_DOCUMENTO = :NEW.MOV_ST_DOCUMENTO
             AND L.FIL_IN_CODIGO    = :NEW.FIL_IN_CODIGO
             AND (L.LIB_ST_PARCELA IS NULL OR L.LIB_ST_PARCELA = :NEW.MOV_ST_PARCELA)
             AND L.LIB_DT_BAIXA     = TRUNC(:NEW.MOV_DT_DATADOCTO)
             AND L.LIB_CH_STATUS    = 'A'
             AND ROWNUM = 1;
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            vLIB := NULL;
        END;
        IF vLIB IS NOT NULL THEN
          -- LIBERACAO VALIDA: REGISTRA A EXECUCAO (MESMA TRANSACAO DA BAIXA - ROLLBACK CONJUNTO)
          INSERT INTO MEGA.CCS_TB_LIBERA_DATA_BAIXA_EXEC
            (LIBE_IN_CODIGO, LIB_IN_CODIGO, MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO,
             MOV_IN_NUMLANCTO, LIBE_IN_USU_EXECUTOU, LIBE_DT_EXECUCAO, LIBE_RE_VALOR)
          VALUES
            (MEGA.CCS_SEQ_LIBERA_DTBX_EXEC.NEXTVAL, vLIB, :NEW.MOV_TAB_IN_CODIGO, :NEW.MOV_SEQ_IN_CODIGO,
             :NEW.MOV_IN_NUMLANCTO, wUSUARIO, SYSDATE, :NEW.MOV_RE_VALOR);
        ELSE
          RAISE_APPLICATION_ERROR(-20000, 'USUARIO ('|| wUSUARIO ||') NAO POSSUI AUTORIZACAO PARA BAIXAR COM DATA ANTERIOR A '
            || TO_CHAR(vLIMITE, 'DD/MM/YYYY') || ' (' || vDIAS || ' DIAS UTEIS)! SOLICITE A LIBERACAO DO TITULO/DATA NA TELA LIBERACAO DE DATA DE BAIXA.');
        END IF;
   END IF;
 END IF;
END;
/
