-- [13/08/2026 - Alexandre Carvalho] Trava de baixa retroativa (V6 vigente) - espelho do
-- fonte vivo em producao OCPDB493 (a trigger nasceu fora do repo; V1-V5 so em backups
-- CCS_TB_BKP_TRG_DTBAIXA_*). Historico completo: Baixa_Retroativa_Liberacao_Quality.md.
CREATE OR REPLACE TRIGGER MEGA.CCS_T_DATA_BAIXA
  BEFORE INSERT ON MEGA.FIN_MOVIMENTO
FOR EACH ROW
DECLARE
    wUSUARIO     NUMBER;
    vLIB         NUMBER;
    vLIMITE      DATE;
    vDIAS        NUMBER;
    vRECEB       BOOLEAN := FALSE;
BEGIN
   -- VERIFICA O USUARIO QUE ESTA LOGADO NO CONTEXTO.
   wUSUARIO := TO_NUMBER(MEGA.GLO_PCK_CONTEXTO.F_GETVARIAVEL('vUSU_IN_CODIGO'));
 -- [23/07/2026 - ALEXANDRE CARVALHO] V5:
 --  * JANELA DE DIAS UTEIS AGORA VEM DO PARAMETRO LIB_BAIXA_DIAS_UTEIS (MEGA.CCS_TB_GFIN_PARAM,
 --    TELA PARAMETROS DA LIBERACAO DE DATA DE BAIXA DO GESTOR FINANCEIRO). FALLBACK = 3.
 --  * FLAG GRU_ST_BAIXA_DATAANT REMOVIDA DA REGRA - TODOS OBEDECEM A MESMA REGRA NA INDUSTRIA.
 --  * FILIAIS DE VAREJO (401,402,403,404,501,502,503,504) FORA DA REGRA.
 --  * MANTIDO: LIBERACAO PONTUAL TITULO+DATA (CCS_TB_LIBERA_DATA_BAIXA 'A' + EXEC),
 --    LOG FIN_MOVIMENTO_BAIXA_LOG, BYPASS DE PROCESSOS SEM USUARIO NO CONTEXTO (NULO/0).
 --  * BACKUPS: CCS_TB_BKP_TRG_DTBAIXA_10072026 (ORIGINAL) / _V3_10072026 (V3) / _23072026 (V4).
 -- [13/08/2026 - ALEXANDRE CARVALHO] V6: ENTRADA DE DEVOLUCAO DE CLIENTE (ACAO 327, TPD ADCLI)
 --  NAO PODE SER TRAVADA - O RECEBIMENTO BAIXA O TITULO ORIGINAL COM A DATA ANTIGA DELE E O
 --  OPERADOR NAO TEM COMO ESCOLHER OUTRA DATA. AS LINHAS FINANCEIRAS DA DEVOLUCAO NAO CARREGAM
 --  A ACAO 327 (CARREGAM 704/715 DO FINANCEIRO), ENTAO O GATE E PELA PILHA DE CHAMADAS:
 --  INSERT VINDO DE MEGA.P_PROCESSOPENDENTERECEBIMENTO (MOTOR DO RECEBIMENTO) PASSA SEM TRAVA,
 --  MAS AINDA GRAVA O LOG FIN_MOVIMENTO_BAIXA_LOG (AUDITORIA). BAIXA MANUAL SEGUE TRAVADA.
 --  BACKUP DA V5: CCS_TB_BKP_TRG_DTBAIXA_13082026.
 IF (:NEW.CONT_TAC_ST_CODIGO IN ('BXCRE','MVFIN','MVCRE'))
    AND :NEW.TPD_ST_CODIGO IN ('CREDITO')
    AND (:NEW.MOV_DT_DATADOCTO < TRUNC(SYSDATE))
    AND :NEW.FIL_IN_CODIGO NOT IN (401,402,403,404,501,502,503,504) THEN
   BEGIN
         INSERT INTO MEGA.FIN_MOVIMENTO_BAIXA_LOG
         (ORG_TAB_IN_CODIGO,   ORG_PAD_IN_CODIGO,       ORG_IN_CODIGO,         ORG_TAU_ST_CODIGO,
          MOV_TAB_IN_CODIGO,   MOV_SEQ_IN_CODIGO,       MOV_IN_NUMLANCTO,      CONT_TAB_IN_CODIGO,
          CONT_PAD_IN_CODIGO,  CONT_TAC_ST_CODIGO,      CONT_CON_IN_SEQUENCIA, DATA,
          USU_IN_CODIGO)
          VALUES
          (:NEW.ORG_TAB_IN_CODIGO,   :NEW.ORG_PAD_IN_CODIGO,       :NEW.ORG_IN_CODIGO,         :NEW.ORG_TAU_ST_CODIGO,
           :NEW.MOV_TAB_IN_CODIGO,   :NEW.MOV_SEQ_IN_CODIGO,       :NEW.MOV_IN_NUMLANCTO,      :NEW.CONT_TAB_IN_CODIGO,
           :NEW.CONT_PAD_IN_CODIGO,  :NEW.CONT_TAC_ST_CODIGO,      :NEW.CONT_CON_IN_SEQUENCIA,  SYSDATE,
           wUSUARIO);
   END;
   -- [13/08/2026 - ALEXANDRE CARVALHO] V6: FLUXO DE RECEBIMENTO (DEVOLUCAO DE CLIENTE) PASSA.
   FOR I IN 1..UTL_CALL_STACK.DYNAMIC_DEPTH LOOP
     IF INSTR(UPPER(UTL_CALL_STACK.CONCATENATE_SUBPROGRAM(UTL_CALL_STACK.SUBPROGRAM(I))),
              'P_PROCESSOPENDENTERECEBIMENTO') > 0 THEN
       vRECEB := TRUE;
       EXIT;
     END IF;
   END LOOP;
   IF vRECEB THEN
     RETURN;
   END IF;
   -- JANELA LIVRE DE N DIAS UTEIS PARA TRAS (N = PARAMETRO; F_ANTDIAUTIL DEVOLVE A PROPRIA
   -- DATA SE JA FOR UTIL, POR ISSO O ENCADEAMENTO SOBRE DATA-1 A CADA PASSO).
   BEGIN
     SELECT GREATEST(TRUNC(PARAM_RE_VALOR), 0)
       INTO vDIAS
       FROM MEGA.CCS_TB_GFIN_PARAM
      WHERE PARAM_ST_CHAVE = 'LIB_BAIXA_DIAS_UTEIS';
   EXCEPTION
     WHEN NO_DATA_FOUND THEN vDIAS := 3;
   END;
   vLIMITE := TRUNC(SYSDATE);
   FOR I IN 1..vDIAS LOOP
     vLIMITE := MEGA.F_ANTDIAUTIL(vLIMITE - 1, :NEW.AGN_PAD_IN_CODIGO, :NEW.AGN_IN_CODIGO);
   END LOOP;
   IF (TRUNC(:NEW.MOV_DT_DATADOCTO) < vLIMITE) AND wUSUARIO IS NOT NULL AND wUSUARIO <> 0 THEN
        BEGIN
          SELECT L.LIB_IN_CODIGO
            INTO vLIB
            FROM MEGA.CCS_TB_LIBERA_DATA_BAIXA L
           WHERE L.AGN_IN_CODIGO    = :NEW.AGN_IN_CODIGO
             AND L.LIB_ST_DOCUMENTO = :NEW.MOV_ST_DOCUMENTO
             AND L.FIL_IN_CODIGO    = :NEW.FIL_IN_CODIGO
             AND (L.LIB_ST_PARCELA IS NULL OR L.LIB_ST_PARCELA = :NEW.MOV_ST_PARCELA)
             AND L.LIB_DT_BAIXA     = TRUNC(:NEW.MOV_DT_DATADOCTO)
             AND L.LIB_CH_STATUS    = 'A'
             AND ROWNUM = 1;
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            vLIB := NULL;
        END;
        IF vLIB IS NOT NULL THEN
          -- LIBERACAO VALIDA: REGISTRA A EXECUCAO (MESMA TRANSACAO DA BAIXA - ROLLBACK CONJUNTO)
          INSERT INTO MEGA.CCS_TB_LIBERA_DATA_BAIXA_EXEC
            (LIBE_IN_CODIGO, LIB_IN_CODIGO, MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO,
             MOV_IN_NUMLANCTO, LIBE_IN_USU_EXECUTOU, LIBE_DT_EXECUCAO, LIBE_RE_VALOR)
          VALUES
            (MEGA.CCS_SEQ_LIBERA_DTBX_EXEC.NEXTVAL, vLIB, :NEW.MOV_TAB_IN_CODIGO, :NEW.MOV_SEQ_IN_CODIGO,
             :NEW.MOV_IN_NUMLANCTO, wUSUARIO, SYSDATE, :NEW.MOV_RE_VALOR);
        ELSE
          RAISE_APPLICATION_ERROR(-20000, 'USUARIO ('|| wUSUARIO ||') NAO POSSUI AUTORIZACAO PARA BAIXAR COM DATA ANTERIOR A '
            || TO_CHAR(vLIMITE, 'DD/MM/YYYY') || ' (' || vDIAS || ' DIAS UTEIS)! SOLICITE A LIBERACAO DO TITULO/DATA NA TELA LIBERACAO DE DATA DE BAIXA.');
        END IF;
   END IF;
 END IF;
END;
/
