/* =====================================================================================================================
   [21/09/2026 - Alexandre Carvalho] GESTOR FINANCEIRO - BAIXA AUTOMATICA DE CONTAS A PAGAR A PARTIR DO EXTRATO DO BANCO
   Tela: Baixas/Conciliacao > Extrato do banco x Mega > botao "Baixar no Mega".

   ESPELHA A BAIXA MANUAL DO MEGA (dissecada em 21/09/2026 - titulo Metrica 575/001, e medida em 4.900 baixas de 45 dias):
     GLO_ACAOMOVIMENTO  1 linha, acao 705, FORM_IN_ID 14001, VALORCONTABIL = VALORFINANC = valor.
                        VALORCONTABILREAL = 0  -> "PENDENTE DE CONTABILIZAR". No Mega REAL = CONTABIL significa "ja tem
                        lancamento contabil" (8.331 de 8.331 casos) e REAL = 0 significa "pendente" (2.762 de 2.762).
                        A baixa gravada por fora NAO gera CON_LANCAMENTO (quem gera e a tela do Mega), entao a marca
                        honesta e a de pendente - a rotina de contabilizacao do Mega enxerga e contabiliza.
     MOV FIN (banco)    acao 705, CONT MVFIN/2, agente = conta (TAU 'N'), TPD PGTOM, natureza C, origem 'M',
                        documento = numero do proprio lancamento (unico - nao colide com o numerador por conta do Mega),
                        FIN_MOVFIN com o nominal, classe/ccusto/projeto 9/2 natureza D.
     MOV BX (fornecedor) acao = GLO_ACAO.ACAO_BAIXA_IN_CODIGO da acao do TITULO (510 -> MVCPA/1 | 530 -> MVCPA/14),
                        TPD DEBITO, natureza D, TREF BXCPA, origem 'P', SALDOZERADO 'N', SALDOCPACRE = valor,
                        classe/ccusto/projeto HERDADOS DO TITULO com natureza C.
     FIN_REFERENCIAFIN  BXCPA    centro = BX, ORI = mov FIN, REF = titulo
                        BXFINCPA centro = BX, ORI = titulo,  REF = mov FIN     (no CPA a ordem e o INVERSO do CRE)
     TITULO             MOV_RE_SALDOCPACRE = 0, MOV_BO_SALDOZERADO = 'S'.

   SO BAIXA O CASO SEGURO (o resto a tela ALERTA e o usuario baixa no Mega):
     titulo a pagar aprovado, fora de remessa bancaria (HBK 'NO'), sem rateio (1 classe / 1 ccusto / ate 1 projeto),
     VALOR DO BANCO = SALDO EM ABERTO (baixa integral, sem juros/desconto), data do banco entre hoje-60 e hoje e FORA de
     periodo encerrado (GLO_ENCERRASISTEMA, sistemas 11 Financeiro e 4 Contabilidade, da empresa do titulo),
     usuario com hierarquia no Contas a Pagar (SIS 12) e no Mov. Financeiro (SIS 14).

   OBJETOS:  CCS_TB_GFIN_BAIXA_LOG / CCS_SEQ_GFIN_BAIXA_LOG     trilha + base do estorno
             CCS_P_GFIN_BAIXA_CPA_X      nucleo (NAO comita, NAO loga, propaga erro) - usado tambem no ensaio com ROLLBACK
             CCS_P_GFIN_BAIXA_CPA        o que a API chama: savepoint + nucleo + log + commit | P_SIMULAR='S' desfaz tudo
             CCS_P_GFIN_ESTORNO_BAIXA_X  nucleo do estorno     |  CCS_P_GFIN_ESTORNO_BAIXA  o que a API chama
   SEM ACENTO E SEM COMENTARIO DE LINHA: o fonte sobe pelo gateway SOAP.
   ROLLBACK: DROP PROCEDURE das 4 + DROP TABLE/SEQUENCE (so depois de conferir que nao ha LOG_CH_STATUS = 'B').
   ===================================================================================================================== */
CREATE TABLE MEGA.CCS_TB_GFIN_BAIXA_LOG (
  LOG_IN_CODIGO        NUMBER        NOT NULL,
  LOG_ST_TOKEN         VARCHAR2(40)  NOT NULL,
  LOG_CH_TIPO          CHAR(1)       DEFAULT 'P' NOT NULL,
  LOG_CH_STATUS        CHAR(1)       NOT NULL,
  ORG_IN_CODIGO        NUMBER,
  MOV_SEQ_IN_CODIGO    NUMBER,
  MOV_IN_NUMLANCTO     NUMBER,
  AGN_IN_CODIGO        NUMBER,
  MOV_ST_DOCUMENTO     VARCHAR2(30),
  MOV_ST_PARCELA       VARCHAR2(10),
  FIL_IN_CODIGO        NUMBER,
  CTA_AGN_IN_CODIGO    NUMBER,
  LOG_DT_BAIXA         DATE,
  LOG_RE_VALOR         NUMBER,
  LOG_RE_SALDO_ANT     NUMBER,
  LOG_CH_ZERADO_ANT    CHAR(1),
  BX_MOV_SEQ_IN_CODIGO NUMBER,
  LANCTO_FIN           NUMBER,
  LANCTO_BX            NUMBER,
  ACAOM_IN_SEQUENCIA   NUMBER,
  ACAO_BX_IN_CODIGO    NUMBER,
  USU_IN_CODIGO        NUMBER,
  USU_ST_LOGIN         VARCHAR2(60),
  LOG_DT_INCLUSAO      DATE          DEFAULT SYSDATE NOT NULL,
  EXT_ST_HISTORICO     VARCHAR2(120),
  EXT_ST_DOCUMENTO     VARCHAR2(60),
  EXT_ST_ARQUIVO       VARCHAR2(120),
  LOG_ST_MENSAGEM      VARCHAR2(1500),
  EST_USU_IN_CODIGO    NUMBER,
  EST_USU_ST_LOGIN     VARCHAR2(60),
  EST_DT               DATE,
  CONSTRAINT CCS_PK_GFIN_BAIXA_LOG PRIMARY KEY (LOG_IN_CODIGO),
  CONSTRAINT CCS_UK_GFIN_BAIXA_LOG_TOKEN UNIQUE (LOG_ST_TOKEN),
  CONSTRAINT CCS_CK_GFIN_BAIXA_LOG_ST CHECK (LOG_CH_STATUS IN ('B','E','S','X'))
)
/
CREATE INDEX MEGA.CCS_IX_GFIN_BAIXA_LOG_TIT ON MEGA.CCS_TB_GFIN_BAIXA_LOG (ORG_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO)
/
CREATE SEQUENCE MEGA.CCS_SEQ_GFIN_BAIXA_LOG START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_BAIXA_CPA_X (
    P_ORG        IN  NUMBER,
    P_SEQ        IN  NUMBER,
    P_LANCTO     IN  NUMBER,
    P_CTA        IN  NUMBER,
    P_DATA       IN  DATE,
    P_VALOR      IN  NUMBER,
    P_USU        IN  NUMBER,
    P_HIST       IN  VARCHAR2,
    O_SEQ_BX     OUT NUMBER,
    O_LANCTO_FIN OUT NUMBER,
    O_LANCTO_BX  OUT NUMBER,
    O_ACAOM      OUT NUMBER,
    O_ACAO_BX    OUT NUMBER,
    O_SALDO_ANT  OUT NUMBER,
    O_ZERADO_ANT OUT VARCHAR2,
    O_AGN        OUT NUMBER,
    O_DOC        OUT VARCHAR2,
    O_PARC       OUT VARCHAR2,
    O_FIL        OUT NUMBER
) IS
    /* [21/09/2026 - Alexandre Carvalho] NUCLEO DA BAIXA CPA PELO EXTRATO. NAO COMITA. VER CABECALHO DO 19_baixa_cpa_extrato.sql */
    C_ORG_TAB   CONSTANT NUMBER := 53;
    C_ORG_PAD   CONSTANT NUMBER := 1;
    C_ORG_TAU   CONSTANT VARCHAR2(3) := 'G';
    C_MOV_TAB   CONSTANT NUMBER := 352;
    C_ACAO_TAB  CONSTANT NUMBER := 55;
    C_ACAO_PAD  CONSTANT NUMBER := 1;
    C_ACAO_FIN  CONSTANT NUMBER := 705;
    C_TPD_FIN   CONSTANT VARCHAR2(10) := 'PGTOM';
    C_TPD_BX    CONSTANT VARCHAR2(10) := 'DEBITO';
    C_TREF      CONSTANT VARCHAR2(10) := 'BXCPA';
    T           MEGA.FIN_MOVIMENTO%ROWTYPE;
    W_DATA      DATE := TRUNC(P_DATA);
    W_VALOR     NUMBER := ROUND(P_VALOR, 2);
    W_CTA_PAD   NUMBER;
    W_ACAO_BX   NUMBER;
    W_CONT_SEQ  NUMBER;
    W_HUS_FIN   NUMBER;
    W_HUS_CPA   NUMBER;
    W_NOME      VARCHAR2(100);
    W_N         NUMBER;
    W_NCLA      NUMBER;
    W_NCCF      NUMBER;
    W_NPRO      NUMBER;
    W_SALDO_VW  NUMBER;
    W_SEQ       NUMBER;
    W_ACAOM     NUMBER;
    W_FIN       NUMBER;
    W_BX        NUMBER;
    W_HIST      VARCHAR2(500);
    E_OCUPADO   EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OCUPADO, -54);
BEGIN
    IF W_VALOR IS NULL OR W_VALOR <= 0 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Valor do banco invalido.');
    END IF;
    IF W_DATA IS NULL OR W_DATA > TRUNC(SYSDATE) OR W_DATA < TRUNC(SYSDATE) - 60 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Data do banco fora da janela permitida (de 60 dias atras ate hoje).');
    END IF;
    /* (o periodo encerrado e conferido depois de ler o titulo - depende da empresa/filial dele) */
    /* TITULO: TRAVA A LINHA - SE ALGUEM ESTIVER COM ELE ABERTO NO MEGA, NAO ESPERA */
    BEGIN
        SELECT M.* INTO T
          FROM MEGA.FIN_MOVIMENTO M
         WHERE M.ORG_TAB_IN_CODIGO = C_ORG_TAB AND M.ORG_PAD_IN_CODIGO = C_ORG_PAD AND M.ORG_IN_CODIGO = P_ORG
           AND M.ORG_TAU_ST_CODIGO = C_ORG_TAU AND M.MOV_TAB_IN_CODIGO = C_MOV_TAB AND M.MOV_SEQ_IN_CODIGO = P_SEQ
           AND M.MOV_IN_NUMLANCTO  = P_LANCTO
           FOR UPDATE NOWAIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20100, 'Titulo nao encontrado no Mega.');
        WHEN E_OCUPADO     THEN RAISE_APPLICATION_ERROR(-20100, 'Titulo em uso por outro usuario no Mega. Tente de novo em instantes.');
    END;
    O_SALDO_ANT := NVL(T.MOV_RE_SALDOCPACRE, 0); O_ZERADO_ANT := NVL(T.MOV_BO_SALDOZERADO, 'N');
    O_AGN := T.AGN_IN_CODIGO; O_DOC := T.MOV_ST_DOCUMENTO; O_PARC := T.MOV_ST_PARCELA; O_FIL := T.FIL_IN_CODIGO;
    /* PERIODO ENCERRADO NO MEGA (GLO_ENCERRASISTEMA): 11 = FINANCEIRO, 4 = CONTABILIDADE - NAO GRAVA BAIXA EM MES FECHADO */
    FOR E IN (SELECT X.SIS_IN_CODIGO, X.SIS_DT_ENCERRAMENTO FROM MEGA.GLO_ENCERRASISTEMA X
               WHERE X.ORG_TAB_IN_CODIGO = C_ORG_TAB AND X.ORG_PAD_IN_CODIGO = C_ORG_PAD AND X.ORG_IN_CODIGO = P_ORG AND X.ORG_TAU_ST_CODIGO = C_ORG_TAU
                 AND X.FIL_IN_CODIGO = T.FIL_IN_CODIGO AND X.SIS_IN_CODIGO IN (11, 4) AND W_DATA <= X.SIS_DT_ENCERRAMENTO) LOOP
        RAISE_APPLICATION_ERROR(-20100, 'Periodo encerrado no Mega para a empresa ' || T.FIL_IN_CODIGO || ' ate ' || TO_CHAR(E.SIS_DT_ENCERRAMENTO, 'DD/MM/YYYY') ||
            CASE WHEN E.SIS_IN_CODIGO = 4 THEN ' (Contabilidade).' ELSE ' (Financeiro).' END);
    END LOOP;
    IF T.MOV_CH_ORIGEM <> 'P' OR T.TREF_ST_CODIGO IS NOT NULL OR T.MOV_CH_NATUREZA <> 'C' THEN
        RAISE_APPLICATION_ERROR(-20100, 'O lancamento informado nao e um titulo a pagar.');
    END IF;
    SELECT COUNT(*) INTO W_N FROM MEGA.FIN_CONTASPAGAR C
     WHERE C.ORG_TAB_IN_CODIGO = C_ORG_TAB AND C.ORG_PAD_IN_CODIGO = C_ORG_PAD AND C.ORG_IN_CODIGO = P_ORG AND C.ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND C.MOV_TAB_IN_CODIGO = C_MOV_TAB AND C.MOV_SEQ_IN_CODIGO = P_SEQ AND C.MOV_IN_NUMLANCTO = P_LANCTO;
    IF W_N = 0 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo sem registro no Contas a Pagar.');
    END IF;
    IF NVL(T.MOV_BO_PREVISAO, 'N') <> 'N' THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo de previsao nao pode ser baixado.');
    END IF;
    IF NVL(T.MOV_CH_STATUSMOV, 'A') <> 'A' OR NVL(T.MOV_CH_SITUACAO, 'N') = 'C' THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo cancelado ou inativo.');
    END IF;
    IF NVL(T.MOV_BO_APROVADOADM, 'N') <> 'S' THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo ainda nao aprovado para pagamento no Mega.');
    END IF;
    IF NVL(T.MOV_ST_HBKSTATUS, 'NO') <> 'NO' THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo esta em remessa de pagamento eletronico (' || T.MOV_ST_HBKSTATUS || '). A baixa vem pelo retorno do banco.');
    END IF;
    IF O_SALDO_ANT <= 0 OR O_ZERADO_ANT = 'S' THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo ja esta baixado.');
    END IF;
    IF ABS(O_SALDO_ANT - W_VALOR) >= 0.005 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Valor do banco (' || TO_CHAR(W_VALOR, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') ||
            ') diferente do saldo do titulo (' || TO_CHAR(O_SALDO_ANT, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || '). Baixa parcial ou com juros/desconto e feita no Mega.');
    END IF;
    /* CONFERE O SALDO PELA VISAO OFICIAL DO MEGA (A MESMA QUE A TELA DO GESTOR USA PARA SUGERIR) */
    BEGIN
        SELECT V.SALDO_EM_ABERTO INTO W_SALDO_VW FROM MEGA.FIN_VW_CONTASPAGAR V
         WHERE V.ORG_IN_CODIGO = P_ORG AND V.MOV_TAB_IN_CODIGO = C_MOV_TAB AND V.MOV_SEQ_IN_CODIGO = P_SEQ AND V.MOV_IN_NUMLANCTO = P_LANCTO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN W_SALDO_VW := NULL;
        WHEN TOO_MANY_ROWS THEN W_SALDO_VW := NULL;
    END;
    IF W_SALDO_VW IS NULL OR ABS(W_SALDO_VW - W_VALOR) >= 0.005 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Saldo em aberto do titulo nao confere com o valor do banco (visao do Contas a Pagar).');
    END IF;
    /* RATEIO: ESTA VERSAO SO BAIXA TITULO COM 1 CLASSE / 1 CENTRO DE CUSTO / ATE 1 PROJETO (96% DOS TITULOS) */
    SELECT COUNT(*) INTO W_NCLA FROM MEGA.FIN_LANCCLASSE L WHERE L.ORG_TAB_IN_CODIGO = C_ORG_TAB AND L.ORG_PAD_IN_CODIGO = C_ORG_PAD AND L.ORG_IN_CODIGO = P_ORG
       AND L.ORG_TAU_ST_CODIGO = C_ORG_TAU AND L.MOV_TAB_IN_CODIGO = C_MOV_TAB AND L.MOV_SEQ_IN_CODIGO = P_SEQ AND L.MOV_IN_NUMLANCTO = P_LANCTO;
    SELECT COUNT(*) INTO W_NCCF FROM MEGA.FIN_LANCCCUSTO L WHERE L.ORG_TAB_IN_CODIGO = C_ORG_TAB AND L.ORG_PAD_IN_CODIGO = C_ORG_PAD AND L.ORG_IN_CODIGO = P_ORG
       AND L.ORG_TAU_ST_CODIGO = C_ORG_TAU AND L.MOV_TAB_IN_CODIGO = C_MOV_TAB AND L.MOV_SEQ_IN_CODIGO = P_SEQ AND L.MOV_IN_NUMLANCTO = P_LANCTO;
    SELECT COUNT(*) INTO W_NPRO FROM MEGA.FIN_LANCPROJ L WHERE L.ORG_TAB_IN_CODIGO = C_ORG_TAB AND L.ORG_PAD_IN_CODIGO = C_ORG_PAD AND L.ORG_IN_CODIGO = P_ORG
       AND L.ORG_TAU_ST_CODIGO = C_ORG_TAU AND L.MOV_TAB_IN_CODIGO = C_MOV_TAB AND L.MOV_SEQ_IN_CODIGO = P_SEQ AND L.MOV_IN_NUMLANCTO = P_LANCTO;
    IF W_NCLA <> 1 OR W_NCCF <> 1 OR W_NPRO > 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Titulo com rateio de classe/centro de custo (' || W_NCLA || '/' || W_NCCF || '/' || W_NPRO || '). Baixe pelo Mega.');
    END IF;
    /* CONTA FINANCEIRA */
    BEGIN
        SELECT C.AGN_PAD_IN_CODIGO INTO W_CTA_PAD FROM MEGA.GLO_CONTASFIN C
         WHERE C.AGN_TAB_IN_CODIGO = C_ORG_TAB AND C.AGN_IN_CODIGO = P_CTA AND C.AGN_TAU_ST_CODIGO = 'N' AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20100, 'Conta financeira ' || P_CTA || ' nao encontrada no Mega.');
    END;
    /* ACAO DA BAIXA = A CONFIGURADA NA ACAO DO TITULO (GLO_ACAO.ACAO_BAIXA_IN_CODIGO) */
    BEGIN
        SELECT A.ACAO_BAIXA_IN_CODIGO INTO W_ACAO_BX FROM MEGA.GLO_ACAO A
         WHERE A.ACAO_TAB_IN_CODIGO = T.ACAO_TAB_IN_CODIGO AND A.ACAO_PAD_IN_CODIGO = T.ACAO_PAD_IN_CODIGO AND A.ACAO_IN_CODIGO = T.ACAO_IN_CODIGO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN W_ACAO_BX := NULL;
    END;
    IF W_ACAO_BX = 510 THEN W_CONT_SEQ := 1;
    ELSIF W_ACAO_BX = 530 THEN W_CONT_SEQ := 14;
    ELSE
        RAISE_APPLICATION_ERROR(-20100, 'Acao do titulo (' || T.ACAO_IN_CODIGO || ') sem acao de baixa conhecida (' || NVL(TO_CHAR(W_ACAO_BX), 'vazia') || '). Baixe pelo Mega.');
    END IF;
    O_ACAO_BX := W_ACAO_BX;
    /* USUARIO: PRECISA PODER BAIXAR NO MEGA (HIERARQUIA NO CONTAS A PAGAR E NO MOV. FINANCEIRO) */
    BEGIN
        SELECT MIN(H.HUS_IN_SEQUENCIA) INTO W_HUS_FIN FROM MEGA.GLO_HIERARQUIAUSUARIO H WHERE H.SIS_IN_CODIGO = 14 AND H.GRU_IN_CODIGO = P_USU;
        SELECT MIN(H.HUS_IN_SEQUENCIA) INTO W_HUS_CPA FROM MEGA.GLO_HIERARQUIAUSUARIO H WHERE H.SIS_IN_CODIGO = 12 AND H.GRU_IN_CODIGO = P_USU;
    END;
    IF W_HUS_FIN IS NULL OR W_HUS_CPA IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'Usuario ' || P_USU || ' sem hierarquia no Mega para baixar (Contas a Pagar / Mov. Financeiro).');
    END IF;
    SELECT SUBSTR(MAX(A.AGN_ST_NOME), 1, 100) INTO W_NOME FROM MEGA.GLO_AGENTES A
     WHERE A.AGN_TAB_IN_CODIGO = T.AGN_TAB_IN_CODIGO AND A.AGN_PAD_IN_CODIGO = T.AGN_PAD_IN_CODIGO AND A.AGN_IN_CODIGO = T.AGN_IN_CODIGO;
    W_HIST := SUBSTR('BAIXA AUTOMATICA PELO EXTRATO (GESTOR FINANCEIRO)' || CASE WHEN P_HIST IS NOT NULL THEN ' - ' || P_HIST END, 1, 500);

    FIN_PCK_MOVIMENTO.COMP_ST_NOME  := 'MEGA';
    FIN_PCK_MOVIMENTO.USU_IN_CODIGO := P_USU;
    W_SEQ   := PCK_MEGA.ACHASEQUENCIADATABELA(P_ORG, C_MOV_TAB, W_DATA);
    W_ACAOM := PCK_MEGA.PROXIMASEQUENCIATAB(59);
    W_FIN   := PCK_MEGA.PROXIMASEQUENCIATAB(C_MOV_TAB);
    W_BX    := PCK_MEGA.PROXIMASEQUENCIATAB(C_MOV_TAB);
    IF W_SEQ IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'Sem sequencia de movimento para a data ' || TO_CHAR(W_DATA, 'DD/MM/YYYY') || ' (periodo fechado?).');
    END IF;
    O_SEQ_BX := W_SEQ; O_ACAOM := W_ACAOM; O_LANCTO_FIN := W_FIN; O_LANCTO_BX := W_BX;

    INSERT INTO GLO_ACAOMOVIMENTO
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      ACAOM_IN_SEQUENCIA, ACAO_TAB_IN_CODIGO, ACAO_PAD_IN_CODIGO, ACAO_IN_CODIGO,
      ACAOM_ST_DOCUMENTO, ACAOM_DT_DATAEMISSAO, ACAOM_DT_DATAENTRADA, USU_IN_INCLUSAO,
      USU_IN_ALTERACAO, ACAOM_DT_INCLUSAO, ACAOM_DT_ALTERACAO, ACAOM_RE_VALORCONTABIL,
      ACAOM_RE_VALORCONTABILREAL, ACAOM_RE_VALORFISCAL, ACAOM_RE_VALORFISCALREAL,
      ACAOM_RE_VALORFINANC, ACAOM_RE_VALORFINANCREAL, ACAOM_RE_VALORIMOB,
      ACAOM_RE_VALORIMOBREAL, CONT_ORG_IN_CODIGO, FIL_IN_CODIGO, LAN_CH_TIPOCONTAB, FORM_IN_ID )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      W_ACAOM, C_ACAO_TAB, C_ACAO_PAD, C_ACAO_FIN,
      TO_CHAR(W_FIN), W_DATA, W_DATA, P_USU,
      P_USU, SYSDATE, SYSDATE, W_VALOR,
      0, 0, 0,
      W_VALOR, 0, 0,
      0, P_ORG, T.FIL_IN_CODIGO, 'S', 14001 );

    /* MOV FIN - SAIDA DA CONTA */
    INSERT INTO FIN_MOVIMENTO
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CONT_TAB_IN_CODIGO, CONT_PAD_IN_CODIGO, CONT_TAC_ST_CODIGO, CONT_CON_IN_SEQUENCIA,
      ACAO_TAB_IN_CODIGO, ACAO_PAD_IN_CODIGO, ACAO_IN_CODIGO, ACAOM_IN_SEQUENCIA,
      IND_IN_CODIGOMOE,
      AGN_TAB_IN_CODIGO, AGN_PAD_IN_CODIGO, AGN_IN_CODIGO, AGN_TAU_ST_CODIGO,
      TPD_ST_CODIGO, MOV_ST_DOCUMENTO, MOV_CH_SONUMEROS,
      MOV_DT_DATADOCTO, MOV_DT_ENTRADA, MOV_DT_VENCTO, MOV_DT_PRORROGADO, MOV_DT_ORCAMENTO,
      MOV_RE_VALOR, MOV_RE_VALORCRE, MOV_RE_VALORDEB, MOV_CH_NATUREZA,
      MOV_CH_STATUSSALDO, MOV_CH_SITUACAO, MOV_CH_STATUSMOV, MOV_BO_PREVISAO,
      MOV_DT_DATAINC, MOV_DT_DATAALT, MOV_CH_STATUSBXREF,
      USU_IN_INCLUSAO, USU_IN_ALTERACAO,
      MOV_RE_VALORMOE, MOV_RE_VALORCREMOE, MOV_RE_VALORDEBMOE,
      IND_IN_CODIGOIND, MOV_RE_COTACAOMOE,
      MOV_CH_ORIGEM, MOV_BO_APROVADOADM, MOV_BO_TITRECONHECIDO, MOV_BO_PAGLIBTESOUR,
      HIS_TAB_IN_CODIGO, HIS_PAD_IN_CODIGO, HIS_IN_REDUZIDO,
      MOV_CH_CONCILIADO, FIL_IN_CODIGO,
      MOV_ST_HBKSTATUS, HUS_IN_SEQUENCIA, MOV_BO_BXCHDEVOL, MOV_RE_VALORMOEDA,
      MOV_ST_COMPLHIST, MOV_BO_SALDOZERADO, MOV_CH_SITDESCDUPL, MOV_RE_SALDOCPACRE )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      40, 1, 'MVFIN', 2,
      C_ACAO_TAB, C_ACAO_PAD, C_ACAO_FIN, W_ACAOM,
      0,
      C_ORG_TAB, W_CTA_PAD, P_CTA, 'N',
      C_TPD_FIN, TO_CHAR(W_FIN), 'S',
      W_DATA, W_DATA, W_DATA, W_DATA, W_DATA,
      W_VALOR, W_VALOR, 0, 'C',
      'N', 'N', 'A', 'N',
      SYSDATE, SYSDATE, 'N',
      P_USU, P_USU,
      W_VALOR, W_VALOR, 0,
      0, 1,
      'M', 'S', 'S', 'N',
      0, 0, 0,
      'N', T.FIL_IN_CODIGO,
      'NO', W_HUS_FIN, 'N', 0,
      W_HIST, 'N', 'N', 0 );
    INSERT INTO FIN_MOVFIN
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      TPD_ST_CODIGO, MVF_ST_NUMERODOC, MVF_ST_NOMINAL, MVF_BO_IMPRESSO )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      C_TPD_FIN, TO_CHAR(W_FIN), W_NOME, 'N' );
    INSERT INTO FIN_LANCCLASSE
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CLA_TAB_IN_CODIGO, CLA_PAD_IN_CODIGO, CLA_IDE_ST_CODIGO, CLA_IN_REDUZIDO,
      LCL_CH_NATUREZA, LCL_RE_PERCENTUAL, LCL_RE_VALOR, LCL_RE_VALORCRE, LCL_RE_VALORDEB,
      LCL_CH_STATUSBXREF, LCL_RE_VALORMOE, LCL_RE_VALORCREMOE, LCL_RE_VALORDEBMOE )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      350, 1, '9', 2,
      'D', 100, W_VALOR, 0, W_VALOR,
      'N', W_VALOR, 0, W_VALOR );
    INSERT INTO FIN_LANCCCUSTO
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CLA_TAB_IN_CODIGO, CLA_PAD_IN_CODIGO, CLA_IDE_ST_CODIGO, CLA_IN_REDUZIDO,
      LCL_CH_NATUREZA, LCC_IN_NUMERO,
      CCF_TAB_IN_CODIGO, CCF_PAD_IN_CODIGO, CCF_IDE_ST_CODIGO, CCF_IN_REDUZIDO,
      LCC_RE_PERCENTUAL, LCC_RE_VALOR, LCC_RE_VALORCRE, LCC_RE_VALORDEB,
      LCC_CH_STATUSBXREF, LCC_RE_VALORMOE, LCC_RE_VALORCREMOE, LCC_RE_VALORDEBMOE )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      350, 1, '9', 2,
      'D', 1,
      2, 1, '9', 2,
      100, W_VALOR, 0, W_VALOR,
      'N', W_VALOR, 0, W_VALOR );
    INSERT INTO FIN_LANCPROJ
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CLA_TAB_IN_CODIGO, CLA_PAD_IN_CODIGO, CLA_IDE_ST_CODIGO, CLA_IN_REDUZIDO,
      LCL_CH_NATUREZA, LCC_IN_NUMERO, LPR_IN_NUMERO,
      PRO_TAB_IN_CODIGO, PRO_PAD_IN_CODIGO, PRO_IDE_ST_CODIGO, PRO_IN_REDUZIDO,
      LPR_RE_PERCENTUAL, LPR_RE_VALOR, LPR_RE_VALORCRE, LPR_RE_VALORDEB,
      LPR_CH_STATUSBXREF, LPR_RE_VALORMOE, LPR_RE_VALORCREMOE, LPR_RE_VALORDEBMOE )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      350, 1, '9', 2,
      'D', 1, 1,
      57, 1, '9', 2,
      100, W_VALOR, 0, W_VALOR,
      'N', W_VALOR, 0, W_VALOR );
    FIN_PCK_MOVIMENTO.REFAZENDOFIN := 'S';
    FIN_PCK_MOVIMENTO.REFAZENDOORC := 'N';
    FIN_PCK_MOVIMENTO.ORCREFAZ     := 0;
    FIN_PCK_MOVIMENTO.P_ATUALIZAMOVIMENTO(
        PMOV_DT_DATADOCTO => W_DATA, PMOV_DT_ENTRADA => W_DATA, PMOV_DT_VENCTO => W_DATA, PMOV_DT_PRORROGADO => W_DATA, PMOV_DT_ORCAMENTO => W_DATA,
        PMOV_TAB_IN_CODIGO => C_MOV_TAB, PMOV_SEQ_IN_CODIGO => W_SEQ, PMOV_IN_NUMLANCTO => W_FIN,
        PBAN_IN_NUMERO => 0, PIND_IN_CODIGOMOE => 0, PORG_IN_CODIGO => P_ORG, PFIL_IN_CODIGO => T.FIL_IN_CODIGO,
        PAGN_TAB_IN_CODIGO => C_ORG_TAB, PAGN_PAD_IN_CODIGO => W_CTA_PAD, PAGN_IN_CODIGO => P_CTA, PAGN_TAU_ST_CODIGO => 'N',
        PMOV_BO_PREVISAO => 'N', PTREF_ST_CODIGO => NULL, PMOV_CH_ORIGEM => 'M', PMOV_CH_NATUREZA => 'C',
        PMOV_RE_VALOR => W_VALOR, PMOV_RE_VALORMOE => W_VALOR, PCRI_IN_CODIGO => -1, PFATOR => 1);

    /* MOV BX - BAIXA NO FORNECEDOR */
    INSERT INTO FIN_MOVIMENTO
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CONT_TAB_IN_CODIGO, CONT_PAD_IN_CODIGO, CONT_TAC_ST_CODIGO, CONT_CON_IN_SEQUENCIA,
      ACAO_TAB_IN_CODIGO, ACAO_PAD_IN_CODIGO, ACAO_IN_CODIGO, ACAOM_IN_SEQUENCIA,
      IND_IN_CODIGOMOE,
      AGN_TAB_IN_CODIGO, AGN_PAD_IN_CODIGO, AGN_IN_CODIGO, AGN_TAU_ST_CODIGO,
      TPD_ST_CODIGO, MOV_ST_DOCUMENTO, MOV_CH_SONUMEROS,
      MOV_DT_DATADOCTO, MOV_DT_ENTRADA, MOV_DT_VENCTO, MOV_DT_PRORROGADO, MOV_DT_ORCAMENTO,
      MOV_RE_VALOR, MOV_RE_VALORCRE, MOV_RE_VALORDEB, MOV_CH_NATUREZA,
      MOV_CH_STATUSSALDO, MOV_CH_SITUACAO, MOV_CH_STATUSMOV, MOV_BO_PREVISAO,
      MOV_DT_DATAINC, MOV_DT_DATAALT, MOV_CH_STATUSBXREF,
      USU_IN_INCLUSAO, USU_IN_ALTERACAO,
      MOV_RE_VALORMOE, MOV_RE_VALORCREMOE, MOV_RE_VALORDEBMOE,
      IND_IN_CODIGOIND, MOV_RE_COTACAOMOE,
      TREF_ST_CODIGO, MOV_ST_PARCELA,
      MOV_CH_ORIGEM, MOV_BO_APROVADOADM, MOV_BO_TITRECONHECIDO, MOV_BO_PAGLIBTESOUR,
      MOV_CH_CONCILIADO, FIL_IN_CODIGO,
      MOV_ST_HBKSTATUS, HUS_IN_SEQUENCIA, MOV_BO_BXCHDEVOL, MOV_RE_VALORMOEDA,
      MOV_ST_COMPLHIST, MOV_BO_SALDOZERADO, MOV_CH_SITDESCDUPL, MOV_RE_SALDOCPACRE )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_BX,
      40, 1, 'MVCPA', W_CONT_SEQ,
      C_ACAO_TAB, C_ACAO_PAD, W_ACAO_BX, W_ACAOM,
      0,
      T.AGN_TAB_IN_CODIGO, T.AGN_PAD_IN_CODIGO, T.AGN_IN_CODIGO, T.AGN_TAU_ST_CODIGO,
      C_TPD_BX, T.MOV_ST_DOCUMENTO, NVL(T.MOV_CH_SONUMEROS, 'S'),
      W_DATA, W_DATA, W_DATA, W_DATA, W_DATA,
      W_VALOR, 0, W_VALOR, 'D',
      'N', 'N', 'A', 'N',
      SYSDATE, SYSDATE, 'N',
      P_USU, P_USU,
      W_VALOR, 0, W_VALOR,
      0, 1,
      C_TREF, T.MOV_ST_PARCELA,
      'P', 'S', 'S', 'N',
      'N', T.FIL_IN_CODIGO,
      'NO', W_HUS_CPA, 'N', 0,
      W_HIST, 'N', 'N', W_VALOR );
    INSERT INTO FIN_REFERENCIAFIN
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      REF_ORG_TAB_IN_CODIGO, REF_ORG_PAD_IN_CODIGO, REF_ORG_IN_CODIGO, REF_ORG_TAU_ST_CODIGO,
      REF_MOV_TAB_IN_CODIGO, REF_MOV_SEQ_IN_CODIGO, REF_MOV_IN_NUMLANCTO,
      ORI_ORG_TAB_IN_CODIGO, ORI_ORG_PAD_IN_CODIGO, ORI_ORG_IN_CODIGO, ORI_ORG_TAU_ST_CODIGO,
      ORI_MOV_TAB_IN_CODIGO, ORI_MOV_SEQ_IN_CODIGO, ORI_MOV_IN_NUMLANCTO,
      REF_ST_TIPO )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_BX,
      C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, P_SEQ, P_LANCTO,
      C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      'BXCPA' );
    INSERT INTO FIN_REFERENCIAFIN
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      REF_ORG_TAB_IN_CODIGO, REF_ORG_PAD_IN_CODIGO, REF_ORG_IN_CODIGO, REF_ORG_TAU_ST_CODIGO,
      REF_MOV_TAB_IN_CODIGO, REF_MOV_SEQ_IN_CODIGO, REF_MOV_IN_NUMLANCTO,
      ORI_ORG_TAB_IN_CODIGO, ORI_ORG_PAD_IN_CODIGO, ORI_ORG_IN_CODIGO, ORI_ORG_TAU_ST_CODIGO,
      ORI_MOV_TAB_IN_CODIGO, ORI_MOV_SEQ_IN_CODIGO, ORI_MOV_IN_NUMLANCTO,
      REF_ST_TIPO )
    VALUES
    ( C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_BX,
      C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, W_SEQ, W_FIN,
      C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
      C_MOV_TAB, P_SEQ, P_LANCTO,
      'BXFINCPA' );
    /* CLASSE / CENTRO DE CUSTO / PROJETO DO MOV BX: HERDADOS DO TITULO, NATUREZA C (ESPELHO DA NATUREZA D DO MOVIMENTO) */
    INSERT INTO FIN_LANCCLASSE
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CLA_TAB_IN_CODIGO, CLA_PAD_IN_CODIGO, CLA_IDE_ST_CODIGO, CLA_IN_REDUZIDO,
      LCL_CH_NATUREZA, LCL_RE_PERCENTUAL, LCL_RE_VALOR, LCL_RE_VALORCRE, LCL_RE_VALORDEB,
      LCL_CH_STATUSBXREF, LCL_RE_VALORMOE, LCL_RE_VALORCREMOE, LCL_RE_VALORDEBMOE )
    SELECT C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
           C_MOV_TAB, W_SEQ, W_BX,
           L.CLA_TAB_IN_CODIGO, L.CLA_PAD_IN_CODIGO, L.CLA_IDE_ST_CODIGO, L.CLA_IN_REDUZIDO,
           'C', 100, W_VALOR, W_VALOR, 0,
           'N', W_VALOR, W_VALOR, 0
      FROM MEGA.FIN_LANCCLASSE L
     WHERE L.ORG_TAB_IN_CODIGO = C_ORG_TAB AND L.ORG_PAD_IN_CODIGO = C_ORG_PAD AND L.ORG_IN_CODIGO = P_ORG AND L.ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND L.MOV_TAB_IN_CODIGO = C_MOV_TAB AND L.MOV_SEQ_IN_CODIGO = P_SEQ AND L.MOV_IN_NUMLANCTO = P_LANCTO;
    INSERT INTO FIN_LANCCCUSTO
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CLA_TAB_IN_CODIGO, CLA_PAD_IN_CODIGO, CLA_IDE_ST_CODIGO, CLA_IN_REDUZIDO,
      LCL_CH_NATUREZA, LCC_IN_NUMERO,
      CCF_TAB_IN_CODIGO, CCF_PAD_IN_CODIGO, CCF_IDE_ST_CODIGO, CCF_IN_REDUZIDO,
      LCC_RE_PERCENTUAL, LCC_RE_VALOR, LCC_RE_VALORCRE, LCC_RE_VALORDEB,
      LCC_CH_STATUSBXREF, LCC_RE_VALORMOE, LCC_RE_VALORCREMOE, LCC_RE_VALORDEBMOE )
    SELECT C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
           C_MOV_TAB, W_SEQ, W_BX,
           L.CLA_TAB_IN_CODIGO, L.CLA_PAD_IN_CODIGO, L.CLA_IDE_ST_CODIGO, L.CLA_IN_REDUZIDO,
           'C', 1,
           L.CCF_TAB_IN_CODIGO, L.CCF_PAD_IN_CODIGO, L.CCF_IDE_ST_CODIGO, L.CCF_IN_REDUZIDO,
           100, W_VALOR, W_VALOR, 0,
           'N', W_VALOR, W_VALOR, 0
      FROM MEGA.FIN_LANCCCUSTO L
     WHERE L.ORG_TAB_IN_CODIGO = C_ORG_TAB AND L.ORG_PAD_IN_CODIGO = C_ORG_PAD AND L.ORG_IN_CODIGO = P_ORG AND L.ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND L.MOV_TAB_IN_CODIGO = C_MOV_TAB AND L.MOV_SEQ_IN_CODIGO = P_SEQ AND L.MOV_IN_NUMLANCTO = P_LANCTO;
    INSERT INTO FIN_LANCPROJ
    ( ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      MOV_TAB_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      CLA_TAB_IN_CODIGO, CLA_PAD_IN_CODIGO, CLA_IDE_ST_CODIGO, CLA_IN_REDUZIDO,
      LCL_CH_NATUREZA, LCC_IN_NUMERO, LPR_IN_NUMERO,
      PRO_TAB_IN_CODIGO, PRO_PAD_IN_CODIGO, PRO_IDE_ST_CODIGO, PRO_IN_REDUZIDO,
      LPR_RE_PERCENTUAL, LPR_RE_VALOR, LPR_RE_VALORCRE, LPR_RE_VALORDEB,
      LPR_CH_STATUSBXREF, LPR_RE_VALORMOE, LPR_RE_VALORCREMOE, LPR_RE_VALORDEBMOE )
    SELECT C_ORG_TAB, C_ORG_PAD, P_ORG, C_ORG_TAU,
           C_MOV_TAB, W_SEQ, W_BX,
           L.CLA_TAB_IN_CODIGO, L.CLA_PAD_IN_CODIGO, L.CLA_IDE_ST_CODIGO, L.CLA_IN_REDUZIDO,
           'C', 1, 1,
           L.PRO_TAB_IN_CODIGO, L.PRO_PAD_IN_CODIGO, L.PRO_IDE_ST_CODIGO, L.PRO_IN_REDUZIDO,
           100, W_VALOR, W_VALOR, 0,
           'N', W_VALOR, W_VALOR, 0
      FROM MEGA.FIN_LANCPROJ L
     WHERE L.ORG_TAB_IN_CODIGO = C_ORG_TAB AND L.ORG_PAD_IN_CODIGO = C_ORG_PAD AND L.ORG_IN_CODIGO = P_ORG AND L.ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND L.MOV_TAB_IN_CODIGO = C_MOV_TAB AND L.MOV_SEQ_IN_CODIGO = P_SEQ AND L.MOV_IN_NUMLANCTO = P_LANCTO;
    FIN_PCK_MOVIMENTO.REFAZENDOFIN := 'S';
    FIN_PCK_MOVIMENTO.REFAZENDOORC := 'N';
    FIN_PCK_MOVIMENTO.ORCREFAZ     := 0;
    FIN_PCK_MOVIMENTO.P_ATUALIZAMOVIMENTO(
        PMOV_DT_DATADOCTO => W_DATA, PMOV_DT_ENTRADA => W_DATA, PMOV_DT_VENCTO => W_DATA, PMOV_DT_PRORROGADO => W_DATA, PMOV_DT_ORCAMENTO => W_DATA,
        PMOV_TAB_IN_CODIGO => C_MOV_TAB, PMOV_SEQ_IN_CODIGO => W_SEQ, PMOV_IN_NUMLANCTO => W_BX,
        PBAN_IN_NUMERO => 0, PIND_IN_CODIGOMOE => 0, PORG_IN_CODIGO => P_ORG, PFIL_IN_CODIGO => T.FIL_IN_CODIGO,
        PAGN_TAB_IN_CODIGO => T.AGN_TAB_IN_CODIGO, PAGN_PAD_IN_CODIGO => T.AGN_PAD_IN_CODIGO, PAGN_IN_CODIGO => T.AGN_IN_CODIGO, PAGN_TAU_ST_CODIGO => T.AGN_TAU_ST_CODIGO,
        PMOV_BO_PREVISAO => 'N', PTREF_ST_CODIGO => C_TREF, PMOV_CH_ORIGEM => 'P', PMOV_CH_NATUREZA => 'D',
        PMOV_RE_VALOR => W_VALOR, PMOV_RE_VALORMOE => W_VALOR, PCRI_IN_CODIGO => -1, PFATOR => 1);

    /* TITULO QUITADO */
    UPDATE MEGA.FIN_MOVIMENTO
       SET MOV_RE_SALDOCPACRE = 0,
           MOV_BO_SALDOZERADO = 'S'
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ AND MOV_IN_NUMLANCTO = P_LANCTO;
    IF SQL%ROWCOUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Falha ao quitar o titulo (linhas afetadas: ' || SQL%ROWCOUNT || ').');
    END IF;
END CCS_P_GFIN_BAIXA_CPA_X;
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_BAIXA_CPA (
    P_TOKEN   IN VARCHAR2,
    P_ORG     IN NUMBER,
    P_SEQ     IN NUMBER,
    P_LANCTO  IN NUMBER,
    P_CTA     IN NUMBER,
    P_DATA    IN DATE,
    P_VALOR   IN NUMBER,
    P_USU     IN NUMBER,
    P_LOGIN   IN VARCHAR2,
    P_HIST    IN VARCHAR2 DEFAULT NULL,
    P_DOCBCO  IN VARCHAR2 DEFAULT NULL,
    P_ARQ     IN VARCHAR2 DEFAULT NULL,
    P_SIMULAR IN VARCHAR2 DEFAULT 'N'
) IS
    /* [21/09/2026 - Alexandre Carvalho] O QUE A API DO GESTOR CHAMA. NUNCA PROPAGA ERRO DE REGRA: GRAVA O RESULTADO NO LOG
       (B = BAIXADO | S = SIMULADO OK, NADA GRAVADO | X = RECUSADO/ERRO) E A API LE O LOG PELO TOKEN. */
    W_SEQ_BX NUMBER; W_FIN NUMBER; W_BX NUMBER; W_ACAOM NUMBER; W_ACAO_BX NUMBER; W_SALDO NUMBER; W_ZER VARCHAR2(1);
    W_AGN NUMBER; W_DOC VARCHAR2(30); W_PARC VARCHAR2(10); W_FIL NUMBER;
    W_ST CHAR(1); W_MSG VARCHAR2(1500);
BEGIN
    SAVEPOINT SP_GFIN_BAIXA;
    BEGIN
        MEGA.CCS_P_GFIN_BAIXA_CPA_X(P_ORG, P_SEQ, P_LANCTO, P_CTA, P_DATA, P_VALOR, P_USU, P_HIST,
            W_SEQ_BX, W_FIN, W_BX, W_ACAOM, W_ACAO_BX, W_SALDO, W_ZER, W_AGN, W_DOC, W_PARC, W_FIL);
        IF NVL(P_SIMULAR, 'N') = 'S' THEN
            ROLLBACK TO SP_GFIN_BAIXA;
            W_ST := 'S'; W_MSG := 'Simulacao sem erro. Nada foi gravado.';
        ELSE
            W_ST := 'B'; W_MSG := NULL;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            W_MSG := SUBSTR(REGEXP_REPLACE(SQLERRM, '^ORA-20100: ', ''), 1, 1500);
            ROLLBACK TO SP_GFIN_BAIXA;
            W_ST := 'X';
    END;
    INSERT INTO MEGA.CCS_TB_GFIN_BAIXA_LOG
    ( LOG_IN_CODIGO, LOG_ST_TOKEN, LOG_CH_TIPO, LOG_CH_STATUS, ORG_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO,
      AGN_IN_CODIGO, MOV_ST_DOCUMENTO, MOV_ST_PARCELA, FIL_IN_CODIGO, CTA_AGN_IN_CODIGO, LOG_DT_BAIXA, LOG_RE_VALOR,
      LOG_RE_SALDO_ANT, LOG_CH_ZERADO_ANT, BX_MOV_SEQ_IN_CODIGO, LANCTO_FIN, LANCTO_BX, ACAOM_IN_SEQUENCIA, ACAO_BX_IN_CODIGO,
      USU_IN_CODIGO, USU_ST_LOGIN, LOG_DT_INCLUSAO, EXT_ST_HISTORICO, EXT_ST_DOCUMENTO, EXT_ST_ARQUIVO, LOG_ST_MENSAGEM )
    VALUES
    ( MEGA.CCS_SEQ_GFIN_BAIXA_LOG.NEXTVAL, P_TOKEN, 'P', W_ST, P_ORG, P_SEQ, P_LANCTO,
      W_AGN, W_DOC, W_PARC, W_FIL, P_CTA, TRUNC(P_DATA), ROUND(P_VALOR, 2),
      W_SALDO, W_ZER, CASE WHEN W_ST = 'B' THEN W_SEQ_BX END, CASE WHEN W_ST = 'B' THEN W_FIN END, CASE WHEN W_ST = 'B' THEN W_BX END,
      CASE WHEN W_ST = 'B' THEN W_ACAOM END, W_ACAO_BX,
      P_USU, SUBSTR(P_LOGIN, 1, 60), SYSDATE, SUBSTR(P_HIST, 1, 120), SUBSTR(P_DOCBCO, 1, 60), SUBSTR(P_ARQ, 1, 120), W_MSG );
    COMMIT;
END CCS_P_GFIN_BAIXA_CPA;
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_ESTORNO_BAIXA_X (
    P_ORG        IN NUMBER,
    P_SEQ_TIT    IN NUMBER,
    P_LANCTO_TIT IN NUMBER,
    P_SEQ_BX     IN NUMBER,
    P_LANCTO_FIN IN NUMBER,
    P_LANCTO_BX  IN NUMBER,
    P_ACAOM      IN NUMBER,
    P_VALOR      IN NUMBER,
    P_SALDO_ANT  IN NUMBER,
    P_ZERADO_ANT IN VARCHAR2,
    P_USU        IN NUMBER
) IS
    /* [21/09/2026 - Alexandre Carvalho] NUCLEO DO ESTORNO DA BAIXA DO GESTOR. NAO COMITA. SO DESFAZ O QUE AINDA ESTA INTACTO:
       MOV DO BANCO NAO CONCILIADO, ACAO SEM LANCAMENTO CONTABIL, NENHUMA OUTRA REFERENCIA PENDURADA, TITULO AINDA ZERADO. */
    C_ORG_TAB CONSTANT NUMBER := 53; C_ORG_PAD CONSTANT NUMBER := 1; C_ORG_TAU CONSTANT VARCHAR2(3) := 'G'; C_MOV_TAB CONSTANT NUMBER := 352;
    F MEGA.FIN_MOVIMENTO%ROWTYPE;
    B MEGA.FIN_MOVIMENTO%ROWTYPE;
    T MEGA.FIN_MOVIMENTO%ROWTYPE;
    W_N NUMBER;
    E_OCUPADO EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OCUPADO, -54);
    PROCEDURE LE(P_S NUMBER, P_L NUMBER, R OUT MEGA.FIN_MOVIMENTO%ROWTYPE, P_QUE VARCHAR2) IS
    BEGIN
        SELECT M.* INTO R FROM MEGA.FIN_MOVIMENTO M
         WHERE M.ORG_TAB_IN_CODIGO = C_ORG_TAB AND M.ORG_PAD_IN_CODIGO = C_ORG_PAD AND M.ORG_IN_CODIGO = P_ORG AND M.ORG_TAU_ST_CODIGO = C_ORG_TAU
           AND M.MOV_TAB_IN_CODIGO = C_MOV_TAB AND M.MOV_SEQ_IN_CODIGO = P_S AND M.MOV_IN_NUMLANCTO = P_L
           FOR UPDATE NOWAIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20100, P_QUE || ' nao existe mais no Mega (ja excluido por la?).');
        WHEN E_OCUPADO     THEN RAISE_APPLICATION_ERROR(-20100, P_QUE || ' em uso por outro usuario no Mega. Tente de novo em instantes.');
    END;
    PROCEDURE DESATUALIZA(R MEGA.FIN_MOVIMENTO%ROWTYPE) IS
    BEGIN
        FIN_PCK_MOVIMENTO.P_DESATUALIZAMOVIMENTO(
            PMOV_DT_DATADOCTO => R.MOV_DT_DATADOCTO, PMOV_DT_ENTRADA => R.MOV_DT_ENTRADA, PMOV_DT_VENCTO => R.MOV_DT_VENCTO,
            PMOV_DT_PRORROGADO => R.MOV_DT_PRORROGADO, PMOV_DT_ORCAMENTO => R.MOV_DT_ORCAMENTO,
            PMOV_TAB_IN_CODIGO => R.MOV_TAB_IN_CODIGO, PMOV_SEQ_IN_CODIGO => R.MOV_SEQ_IN_CODIGO, PMOV_IN_NUMLANCTO => R.MOV_IN_NUMLANCTO,
            PBAN_IN_NUMERO => 0, PIND_IN_CODIGOMOE => 0, PORG_IN_CODIGO => R.ORG_IN_CODIGO, PFIL_IN_CODIGO => R.FIL_IN_CODIGO,
            PAGN_TAB_IN_CODIGO => R.AGN_TAB_IN_CODIGO, PAGN_PAD_IN_CODIGO => R.AGN_PAD_IN_CODIGO, PAGN_IN_CODIGO => R.AGN_IN_CODIGO,
            PAGN_TAU_ST_CODIGO => R.AGN_TAU_ST_CODIGO, PMOV_BO_PREVISAO => 'N', PTREF_ST_CODIGO => R.TREF_ST_CODIGO,
            PMOV_CH_ORIGEM => R.MOV_CH_ORIGEM, PMOV_CH_NATUREZA => R.MOV_CH_NATUREZA,
            PMOV_RE_VALOR => R.MOV_RE_VALOR, PMOV_RE_VALORMOE => R.MOV_RE_VALORMOE,
            PUPDATEKIND => 'D', PMOV_CH_SITUACAO => R.MOV_CH_SITUACAO, PUSU_IN_ALTERACAO => P_USU,
            PACAOM_IN_SEQUENCIA => R.ACAOM_IN_SEQUENCIA, PMARCAPARACONTABILIZAR => 'N');
    END;
BEGIN
    LE(P_SEQ_TIT, P_LANCTO_TIT, T, 'Titulo');
    LE(P_SEQ_BX, P_LANCTO_FIN, F, 'Lancamento do banco');
    LE(P_SEQ_BX, P_LANCTO_BX, B, 'Lancamento da baixa');
    IF F.ACAOM_IN_SEQUENCIA <> P_ACAOM OR B.ACAOM_IN_SEQUENCIA <> P_ACAOM OR ABS(F.MOV_RE_VALOR - P_VALOR) >= 0.005 OR ABS(B.MOV_RE_VALOR - P_VALOR) >= 0.005 THEN
        RAISE_APPLICATION_ERROR(-20100, 'A baixa foi alterada no Mega depois de gravada. Estorne pelo Mega.');
    END IF;
    IF NVL(F.MOV_CH_CONCILIADO, 'N') = 'S' OR F.CON_IN_SEQUENCIAL IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'O lancamento do banco ja esta conciliado. Desfaca a conciliacao antes de estornar.');
    END IF;
    SELECT COUNT(*) INTO W_N FROM MEGA.CON_LANCAMENTO C WHERE C.ACAOM_ORG_IN_CODIGO = P_ORG AND C.ACAOM_IN_SEQUENCIA = P_ACAOM;
    IF W_N > 0 THEN
        RAISE_APPLICATION_ERROR(-20100, 'A baixa ja foi contabilizada. Estorne pelo Mega.');
    END IF;
    IF NVL(T.MOV_RE_SALDOCPACRE, 0) <> 0 OR NVL(T.MOV_BO_SALDOZERADO, 'N') <> 'S' THEN
        RAISE_APPLICATION_ERROR(-20100, 'O titulo foi movimentado depois da baixa. Estorne pelo Mega.');
    END IF;
    SELECT COUNT(*) INTO W_N FROM MEGA.FIN_REFERENCIAFIN R
     WHERE R.ORG_IN_CODIGO = P_ORG
       AND NOT (R.MOV_TAB_IN_CODIGO = C_MOV_TAB AND R.MOV_SEQ_IN_CODIGO = P_SEQ_BX AND R.MOV_IN_NUMLANCTO = P_LANCTO_BX)
       AND ( (R.REF_MOV_TAB_IN_CODIGO = C_MOV_TAB AND R.REF_MOV_SEQ_IN_CODIGO = P_SEQ_BX AND R.REF_MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX))
          OR (R.ORI_MOV_TAB_IN_CODIGO = C_MOV_TAB AND R.ORI_MOV_SEQ_IN_CODIGO = P_SEQ_BX AND R.ORI_MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX))
          OR (R.MOV_TAB_IN_CODIGO = C_MOV_TAB AND R.MOV_SEQ_IN_CODIGO = P_SEQ_BX AND R.MOV_IN_NUMLANCTO = P_LANCTO_FIN) );
    IF W_N > 0 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Ha outros lancamentos ligados a esta baixa (juros, desconto ou transferencia). Estorne pelo Mega.');
    END IF;

    FIN_PCK_MOVIMENTO.COMP_ST_NOME  := 'MEGA';
    FIN_PCK_MOVIMENTO.USU_IN_CODIGO := P_USU;
    FIN_PCK_MOVIMENTO.REFAZENDOFIN  := 'S';
    FIN_PCK_MOVIMENTO.REFAZENDOORC  := 'N';
    FIN_PCK_MOVIMENTO.ORCREFAZ      := 0;
    DESATUALIZA(B);
    DESATUALIZA(F);

    DELETE FROM MEGA.FIN_REFERENCIAFIN
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_BX AND MOV_IN_NUMLANCTO = P_LANCTO_BX;
    IF SQL%ROWCOUNT <> 2 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Referencias da baixa diferentes do esperado (' || SQL%ROWCOUNT || '). Estorne pelo Mega.');
    END IF;
    DELETE FROM MEGA.FIN_LANCPROJ
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_BX AND MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX);
    DELETE FROM MEGA.FIN_LANCCCUSTO
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_BX AND MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX);
    DELETE FROM MEGA.FIN_LANCCLASSE
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_BX AND MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX);
    DELETE FROM MEGA.FIN_MOVFIN
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_BX AND MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX);
    DELETE FROM MEGA.FIN_MOVIMENTO
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_BX AND MOV_IN_NUMLANCTO IN (P_LANCTO_FIN, P_LANCTO_BX);
    IF SQL%ROWCOUNT <> 2 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Movimentos da baixa diferentes do esperado (' || SQL%ROWCOUNT || ').');
    END IF;
    DELETE FROM MEGA.GLO_ACAOMOVIMENTO
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND ACAOM_IN_SEQUENCIA = P_ACAOM;
    UPDATE MEGA.FIN_MOVIMENTO
       SET MOV_RE_SALDOCPACRE = P_SALDO_ANT,
           MOV_BO_SALDOZERADO = NVL(P_ZERADO_ANT, 'N')
     WHERE ORG_TAB_IN_CODIGO = C_ORG_TAB AND ORG_PAD_IN_CODIGO = C_ORG_PAD AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = C_ORG_TAU
       AND MOV_TAB_IN_CODIGO = C_MOV_TAB AND MOV_SEQ_IN_CODIGO = P_SEQ_TIT AND MOV_IN_NUMLANCTO = P_LANCTO_TIT;
END CCS_P_GFIN_ESTORNO_BAIXA_X;
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_ESTORNO_BAIXA (
    P_LOG   IN NUMBER,
    P_USU   IN NUMBER,
    P_LOGIN IN VARCHAR2
) IS
    /* [21/09/2026 - Alexandre Carvalho] O QUE A API CHAMA PARA DESFAZER UMA BAIXA DO GESTOR. RESULTADO NO PROPRIO LOG:
       STATUS VIRA 'E' SE DESFEZ; SE RECUSOU, STATUS CONTINUA 'B' E O MOTIVO FICA EM LOG_ST_MENSAGEM. */
    R MEGA.CCS_TB_GFIN_BAIXA_LOG%ROWTYPE;
    W_MSG VARCHAR2(1500);
BEGIN
    BEGIN
        SELECT * INTO R FROM MEGA.CCS_TB_GFIN_BAIXA_LOG WHERE LOG_IN_CODIGO = P_LOG AND LOG_CH_STATUS = 'B' FOR UPDATE NOWAIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN;
    END;
    SAVEPOINT SP_GFIN_ESTORNO;
    BEGIN
        MEGA.CCS_P_GFIN_ESTORNO_BAIXA_X(R.ORG_IN_CODIGO, R.MOV_SEQ_IN_CODIGO, R.MOV_IN_NUMLANCTO, R.BX_MOV_SEQ_IN_CODIGO,
            R.LANCTO_FIN, R.LANCTO_BX, R.ACAOM_IN_SEQUENCIA, R.LOG_RE_VALOR, R.LOG_RE_SALDO_ANT, R.LOG_CH_ZERADO_ANT, P_USU);
        UPDATE MEGA.CCS_TB_GFIN_BAIXA_LOG
           SET LOG_CH_STATUS = 'E', EST_USU_IN_CODIGO = P_USU, EST_USU_ST_LOGIN = SUBSTR(P_LOGIN, 1, 60), EST_DT = SYSDATE, LOG_ST_MENSAGEM = NULL
         WHERE LOG_IN_CODIGO = P_LOG;
    EXCEPTION
        WHEN OTHERS THEN
            W_MSG := SUBSTR(REGEXP_REPLACE(SQLERRM, '^ORA-20100: ', ''), 1, 1500);
            ROLLBACK TO SP_GFIN_ESTORNO;
            UPDATE MEGA.CCS_TB_GFIN_BAIXA_LOG SET LOG_ST_MENSAGEM = SUBSTR('ESTORNO RECUSADO: ' || W_MSG, 1, 1500) WHERE LOG_IN_CODIGO = P_LOG;
    END;
    COMMIT;
END CCS_P_GFIN_ESTORNO_BAIXA;
/
