/* =====================================================================================================================
   [21/09/2026 - Alexandre Carvalho] GESTOR FINANCEIRO - CONCILIACAO BANCARIA AUTOMATICA A PARTIR DO EXTRATO DO BANCO
   Tela: Baixas/Conciliacao > Extrato do banco x Mega > botao "Conciliar no Mega".

   ESPELHA O PACOTE NATIVO MEGA.FIN_PCK_CONCILIACAOBANC (f_CriaConciliacao + p_ConciliaMov + p_ConciliaBanco) E A CONCILIACAO
   MANUAL DA TELA DO MEGA (dissecada em 21/09/2026 - CON 20818): UMA CONCILIACAO = 3 COMANDOS
     1) INSERT FIN_CONCILIAMOVIMENTO (FIN_SEQ_CONCILIACAO.NEXTVAL, org 53/1/ORG/'G', conta 53/PAD/AGN/'N', CON_CH_TIPO 'A' = automatica,
        CON_DT_CONCILIACAO = SYSDATE, CON_DT_MAIORDATA = GREATEST(data do banco, MOV_DT_DATADOCTO), usuario, valor)
     2) UPDATE FIN_MOVIMENTO   SET MOV_CH_CONCILIADO = 'S', CON_IN_SEQUENCIAL = :con
     3) UPDATE FIN_CONCILIACAO SET CBA_CH_STATUS     = 'S', CON_IN_SEQUENCIAL = :con
   SO CONCILIA PAR 1 x 1: 1 LINHA DO EXTRATO JA IMPORTADA NO MEGA (FIN_CONCILIACAO) x 1 LANCAMENTO DA MESMA CONTA, MESMO VALOR,
   NATUREZA ESPELHADA (debito no banco = natureza C no Mega), ATE 5 DIAS DE DISTANCIA, NENHUM DOS DOIS JA CONCILIADO, PERIODO ABERTO
   (FIN_PCK_CONCILIACAOBANC.P_VALIDACONCILIACAO - o mesmo teste da tela do Mega). LINHA NAO IMPORTADA NO MEGA: SO ALERTA.
   DESFAZER: SO CONCILIACAO FEITA POR AQUI E AINDA INTACTA (1 movimento + 1 linha do banco): volta 'N'/NULL e apaga a FIN_CONCILIAMOVIMENTO.

   OBJETOS:  CCS_TB_GFIN_CONC_LOG / CCS_SEQ_GFIN_CONC_LOG
             CCS_P_GFIN_CONCILIA_X / CCS_P_GFIN_CONCILIA           nucleo (nao comita) / o que a API chama (log por token, P_SIMULAR)
             CCS_P_GFIN_DESCONCILIA_X / CCS_P_GFIN_DESCONCILIA
   SEM ACENTO E SEM COMENTARIO DE LINHA: o fonte sobe pelo gateway SOAP.
   ROLLBACK: DROP PROCEDURE das 4 + DROP TABLE/SEQUENCE (depois de conferir que nao ha LOG_CH_STATUS = 'C').
   ===================================================================================================================== */
CREATE TABLE MEGA.CCS_TB_GFIN_CONC_LOG (
  LOG_IN_CODIGO      NUMBER        NOT NULL,
  LOG_ST_TOKEN       VARCHAR2(40)  NOT NULL,
  LOG_CH_STATUS      CHAR(1)       NOT NULL,
  ORG_IN_CODIGO      NUMBER,
  MOV_SEQ_IN_CODIGO  NUMBER,
  MOV_IN_NUMLANCTO   NUMBER,
  CBA_IN_SEQUENCIA   NUMBER,
  CON_IN_SEQUENCIAL  NUMBER,
  CTA_AGN_IN_CODIGO  NUMBER,
  LOG_DT_BANCO       DATE,
  LOG_DT_MOVIMENTO   DATE,
  LOG_RE_VALOR       NUMBER,
  USU_IN_CODIGO      NUMBER,
  USU_ST_LOGIN       VARCHAR2(60),
  LOG_DT_INCLUSAO    DATE          DEFAULT SYSDATE NOT NULL,
  EXT_ST_HISTORICO   VARCHAR2(120),
  EXT_ST_ARQUIVO     VARCHAR2(120),
  LOG_ST_MENSAGEM    VARCHAR2(1500),
  DES_USU_IN_CODIGO  NUMBER,
  DES_USU_ST_LOGIN   VARCHAR2(60),
  DES_DT             DATE,
  CONSTRAINT CCS_PK_GFIN_CONC_LOG PRIMARY KEY (LOG_IN_CODIGO),
  CONSTRAINT CCS_UK_GFIN_CONC_LOG_TOKEN UNIQUE (LOG_ST_TOKEN),
  CONSTRAINT CCS_CK_GFIN_CONC_LOG_ST CHECK (LOG_CH_STATUS IN ('C','D','S','X'))
)
/
CREATE INDEX MEGA.CCS_IX_GFIN_CONC_LOG_CON ON MEGA.CCS_TB_GFIN_CONC_LOG (CON_IN_SEQUENCIAL)
/
CREATE SEQUENCE MEGA.CCS_SEQ_GFIN_CONC_LOG START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_CONCILIA_X (
    P_ORG    IN  NUMBER,
    P_SEQ    IN  NUMBER,
    P_LANCTO IN  NUMBER,
    P_CBA    IN  NUMBER,
    P_USU    IN  NUMBER,
    O_CON    OUT NUMBER,
    O_CTA    OUT NUMBER,
    O_VALOR  OUT NUMBER,
    O_DT_BCO OUT DATE,
    O_DT_MOV OUT DATE
) IS
    /* [21/09/2026 - Alexandre Carvalho] NUCLEO DA CONCILIACAO 1 x 1 PELO EXTRATO. NAO COMITA. VER CABECALHO DO 20_conciliacao_extrato.sql */
    M MEGA.FIN_MOVIMENTO%ROWTYPE;
    B MEGA.FIN_CONCILIACAO%ROWTYPE;
    W_HUS  NUMBER;
    W_CON  NUMBER;
    W_MAIOR DATE;
    E_OCUPADO EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_OCUPADO, -54);
BEGIN
    BEGIN
        SELECT X.* INTO M FROM MEGA.FIN_MOVIMENTO X
         WHERE X.ORG_TAB_IN_CODIGO = 53 AND X.ORG_PAD_IN_CODIGO = 1 AND X.ORG_IN_CODIGO = P_ORG AND X.ORG_TAU_ST_CODIGO = 'G'
           AND X.MOV_TAB_IN_CODIGO = 352 AND X.MOV_SEQ_IN_CODIGO = P_SEQ AND X.MOV_IN_NUMLANCTO = P_LANCTO
           FOR UPDATE NOWAIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20100, 'Lancamento nao encontrado no Mega.');
        WHEN E_OCUPADO     THEN RAISE_APPLICATION_ERROR(-20100, 'Lancamento em uso por outro usuario no Mega. Tente de novo em instantes.');
    END;
    BEGIN
        SELECT X.* INTO B FROM MEGA.FIN_CONCILIACAO X WHERE X.CBA_IN_SEQUENCIA = P_CBA FOR UPDATE NOWAIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20100, 'Linha do extrato nao encontrada no Mega (o extrato foi importado?).');
        WHEN E_OCUPADO     THEN RAISE_APPLICATION_ERROR(-20100, 'Linha do extrato em uso por outro usuario no Mega. Tente de novo em instantes.');
    END;
    O_CTA := M.AGN_IN_CODIGO; O_VALOR := M.MOV_RE_VALOR; O_DT_BCO := B.CBA_DT_DATA; O_DT_MOV := M.MOV_DT_DATADOCTO;
    IF M.AGN_TAU_ST_CODIGO <> 'N' THEN
        RAISE_APPLICATION_ERROR(-20100, 'O lancamento informado nao e de conta financeira.');
    END IF;
    IF NVL(M.MOV_CH_SITUACAO, 'N') = 'C' OR NVL(M.MOV_BO_PREVISAO, 'N') <> 'N' THEN
        RAISE_APPLICATION_ERROR(-20100, 'Lancamento cancelado ou de previsao nao pode ser conciliado.');
    END IF;
    IF NVL(M.MOV_CH_CONCILIADO, 'N') = 'S' OR M.CON_IN_SEQUENCIAL IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'Este lancamento ja esta conciliado no Mega.');
    END IF;
    IF NVL(B.CBA_CH_STATUS, 'N') = 'S' OR B.CON_IN_SEQUENCIAL IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'Esta linha do extrato ja esta conciliada no Mega.');
    END IF;
    IF B.ORG_IN_CODIGO <> M.ORG_IN_CODIGO OR B.AGN_IN_CODIGO <> M.AGN_IN_CODIGO OR B.AGN_PAD_IN_CODIGO <> M.AGN_PAD_IN_CODIGO THEN
        RAISE_APPLICATION_ERROR(-20100, 'A linha do extrato e o lancamento sao de contas diferentes.');
    END IF;
    IF ABS(NVL(B.CBA_RE_VALOR, 0) - NVL(M.MOV_RE_VALOR, 0)) >= 0.005 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Valor do extrato diferente do valor do lancamento.');
    END IF;
    IF B.CBA_CH_NATUREZA = M.MOV_CH_NATUREZA THEN
        RAISE_APPLICATION_ERROR(-20100, 'Natureza nao confere: saida no banco precisa de lancamento de saida no Mega (e entrada de entrada).');
    END IF;
    IF ABS(TRUNC(B.CBA_DT_DATA) - TRUNC(M.MOV_DT_VENCTO)) > 5 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Data do extrato e data do lancamento com mais de 5 dias de distancia.');
    END IF;
    SELECT MIN(H.HUS_IN_SEQUENCIA) INTO W_HUS FROM MEGA.GLO_HIERARQUIAUSUARIO H WHERE H.SIS_IN_CODIGO = 14 AND H.GRU_IN_CODIGO = P_USU;
    IF W_HUS IS NULL THEN
        RAISE_APPLICATION_ERROR(-20100, 'Usuario ' || P_USU || ' sem hierarquia no Mov. Financeiro do Mega para conciliar.');
    END IF;
    W_MAIOR := GREATEST(TRUNC(B.CBA_DT_DATA), TRUNC(M.MOV_DT_DATADOCTO));
    /* MESMO TESTE DE PERIODO ENCERRADO DA TELA DO MEGA */
    BEGIN
        MEGA.FIN_PCK_CONCILIACAOBANC.P_VALIDACONCILIACAO(P_ORG, M.FIL_IN_CODIGO, LEAST(TRUNC(B.CBA_DT_DATA), TRUNC(M.MOV_DT_DATADOCTO)));
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20100, 'Periodo encerrado no Financeiro do Mega para a empresa ' || M.FIL_IN_CODIGO || '.');
    END;

    SELECT MEGA.FIN_SEQ_CONCILIACAO.NEXTVAL INTO W_CON FROM DUAL;
    INSERT INTO MEGA.FIN_CONCILIAMOVIMENTO
    ( CON_IN_SEQUENCIAL, ORG_TAB_IN_CODIGO, ORG_PAD_IN_CODIGO, ORG_IN_CODIGO, ORG_TAU_ST_CODIGO,
      AGN_TAB_IN_CODIGO, AGN_PAD_IN_CODIGO, AGN_IN_CODIGO, AGN_TAU_ST_CODIGO,
      CON_CH_TIPO, CON_DT_CONCILIACAO, CON_DT_MAIORDATA, USU_IN_CODIGO, CON_RE_VALOR )
    VALUES
    ( W_CON, 53, 1, P_ORG, 'G',
      53, M.AGN_PAD_IN_CODIGO, M.AGN_IN_CODIGO, 'N',
      'A', SYSDATE, W_MAIOR, P_USU, M.MOV_RE_VALOR );
    UPDATE MEGA.FIN_MOVIMENTO
       SET MOV_CH_CONCILIADO = 'S',
           CON_IN_SEQUENCIAL = W_CON
     WHERE ORG_TAB_IN_CODIGO = 53 AND ORG_PAD_IN_CODIGO = 1 AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = 'G'
       AND MOV_TAB_IN_CODIGO = 352 AND MOV_SEQ_IN_CODIGO = P_SEQ AND MOV_IN_NUMLANCTO = P_LANCTO;
    IF SQL%ROWCOUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Falha ao marcar o lancamento como conciliado (' || SQL%ROWCOUNT || ').');
    END IF;
    UPDATE MEGA.FIN_CONCILIACAO
       SET CBA_CH_STATUS     = 'S',
           CON_IN_SEQUENCIAL = W_CON
     WHERE CBA_IN_SEQUENCIA  = P_CBA;
    IF SQL%ROWCOUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Falha ao marcar a linha do extrato como conciliada (' || SQL%ROWCOUNT || ').');
    END IF;
    O_CON := W_CON;
END CCS_P_GFIN_CONCILIA_X;
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_CONCILIA (
    P_TOKEN   IN VARCHAR2,
    P_ORG     IN NUMBER,
    P_SEQ     IN NUMBER,
    P_LANCTO  IN NUMBER,
    P_CBA     IN NUMBER,
    P_USU     IN NUMBER,
    P_LOGIN   IN VARCHAR2,
    P_HIST    IN VARCHAR2 DEFAULT NULL,
    P_ARQ     IN VARCHAR2 DEFAULT NULL,
    P_SIMULAR IN VARCHAR2 DEFAULT 'N'
) IS
    /* [21/09/2026 - Alexandre Carvalho] O QUE A API CHAMA. RESULTADO NO LOG PELO TOKEN: C = CONCILIADO | S = SIMULADO OK | X = RECUSADO. */
    W_CON NUMBER; W_CTA NUMBER; W_VALOR NUMBER; W_DB DATE; W_DM DATE; W_ST CHAR(1); W_MSG VARCHAR2(1500);
BEGIN
    SAVEPOINT SP_GFIN_CONC;
    BEGIN
        MEGA.CCS_P_GFIN_CONCILIA_X(P_ORG, P_SEQ, P_LANCTO, P_CBA, P_USU, W_CON, W_CTA, W_VALOR, W_DB, W_DM);
        IF NVL(P_SIMULAR, 'N') = 'S' THEN
            ROLLBACK TO SP_GFIN_CONC;
            W_ST := 'S'; W_MSG := 'Simulacao sem erro. Nada foi gravado.'; W_CON := NULL;
        ELSE
            W_ST := 'C'; W_MSG := NULL;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            W_MSG := SUBSTR(REGEXP_REPLACE(SQLERRM, '^ORA-20100: ', ''), 1, 1500);
            ROLLBACK TO SP_GFIN_CONC;
            W_ST := 'X'; W_CON := NULL;
    END;
    INSERT INTO MEGA.CCS_TB_GFIN_CONC_LOG
    ( LOG_IN_CODIGO, LOG_ST_TOKEN, LOG_CH_STATUS, ORG_IN_CODIGO, MOV_SEQ_IN_CODIGO, MOV_IN_NUMLANCTO, CBA_IN_SEQUENCIA, CON_IN_SEQUENCIAL,
      CTA_AGN_IN_CODIGO, LOG_DT_BANCO, LOG_DT_MOVIMENTO, LOG_RE_VALOR, USU_IN_CODIGO, USU_ST_LOGIN, LOG_DT_INCLUSAO, EXT_ST_HISTORICO, EXT_ST_ARQUIVO, LOG_ST_MENSAGEM )
    VALUES
    ( MEGA.CCS_SEQ_GFIN_CONC_LOG.NEXTVAL, P_TOKEN, W_ST, P_ORG, P_SEQ, P_LANCTO, P_CBA, W_CON,
      W_CTA, W_DB, W_DM, W_VALOR, P_USU, SUBSTR(P_LOGIN, 1, 60), SYSDATE, SUBSTR(P_HIST, 1, 120), SUBSTR(P_ARQ, 1, 120), W_MSG );
    COMMIT;
END CCS_P_GFIN_CONCILIA;
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_DESCONCILIA_X (
    P_ORG    IN NUMBER,
    P_SEQ    IN NUMBER,
    P_LANCTO IN NUMBER,
    P_CBA    IN NUMBER,
    P_CON    IN NUMBER
) IS
    /* [21/09/2026 - Alexandre Carvalho] DESFAZ UMA CONCILIACAO 1 x 1 FEITA PELO GESTOR, SE AINDA ESTIVER INTACTA. NAO COMITA. */
    W_NM NUMBER; W_NB NUMBER; W_OK NUMBER;
BEGIN
    SELECT COUNT(*) INTO W_NM FROM MEGA.FIN_MOVIMENTO   X WHERE X.CON_IN_SEQUENCIAL = P_CON;
    SELECT COUNT(*) INTO W_NB FROM MEGA.FIN_CONCILIACAO X WHERE X.CON_IN_SEQUENCIAL = P_CON;
    IF W_NM <> 1 OR W_NB <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'A conciliacao foi alterada no Mega (' || W_NM || ' lancamento(s), ' || W_NB || ' linha(s) do banco). Desfaca pelo Mega.');
    END IF;
    SELECT COUNT(*) INTO W_OK FROM MEGA.FIN_CONCILIAMOVIMENTO C WHERE C.CON_IN_SEQUENCIAL = P_CON AND C.CON_CH_TIPO = 'A' AND C.ORG_IN_CODIGO = P_ORG;
    IF W_OK <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'Conciliacao nao encontrada no Mega (ja desfeita por la?).');
    END IF;
    UPDATE MEGA.FIN_MOVIMENTO
       SET MOV_CH_CONCILIADO = 'N',
           CON_IN_SEQUENCIAL = NULL
     WHERE ORG_TAB_IN_CODIGO = 53 AND ORG_PAD_IN_CODIGO = 1 AND ORG_IN_CODIGO = P_ORG AND ORG_TAU_ST_CODIGO = 'G'
       AND MOV_TAB_IN_CODIGO = 352 AND MOV_SEQ_IN_CODIGO = P_SEQ AND MOV_IN_NUMLANCTO = P_LANCTO AND CON_IN_SEQUENCIAL = P_CON;
    IF SQL%ROWCOUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'O lancamento desta conciliacao nao e mais o mesmo. Desfaca pelo Mega.');
    END IF;
    UPDATE MEGA.FIN_CONCILIACAO
       SET CBA_CH_STATUS     = 'N',
           CON_IN_SEQUENCIAL = NULL
     WHERE CBA_IN_SEQUENCIA = P_CBA AND CON_IN_SEQUENCIAL = P_CON;
    IF SQL%ROWCOUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20100, 'A linha do extrato desta conciliacao nao e mais a mesma. Desfaca pelo Mega.');
    END IF;
    DELETE FROM MEGA.FIN_CONCILIAMOVIMENTO WHERE CON_IN_SEQUENCIAL = P_CON;
END CCS_P_GFIN_DESCONCILIA_X;
/
CREATE OR REPLACE PROCEDURE MEGA.CCS_P_GFIN_DESCONCILIA (
    P_LOG   IN NUMBER,
    P_USU   IN NUMBER,
    P_LOGIN IN VARCHAR2
) IS
    /* [21/09/2026 - Alexandre Carvalho] O QUE A API CHAMA PARA DESFAZER. STATUS VIRA 'D'; SE RECUSAR, CONTINUA 'C' COM O MOTIVO NA MENSAGEM. */
    R MEGA.CCS_TB_GFIN_CONC_LOG%ROWTYPE;
    W_MSG VARCHAR2(1500);
BEGIN
    BEGIN
        SELECT * INTO R FROM MEGA.CCS_TB_GFIN_CONC_LOG WHERE LOG_IN_CODIGO = P_LOG AND LOG_CH_STATUS = 'C' FOR UPDATE NOWAIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN;
    END;
    SAVEPOINT SP_GFIN_DESCONC;
    BEGIN
        MEGA.CCS_P_GFIN_DESCONCILIA_X(R.ORG_IN_CODIGO, R.MOV_SEQ_IN_CODIGO, R.MOV_IN_NUMLANCTO, R.CBA_IN_SEQUENCIA, R.CON_IN_SEQUENCIAL);
        UPDATE MEGA.CCS_TB_GFIN_CONC_LOG
           SET LOG_CH_STATUS = 'D', DES_USU_IN_CODIGO = P_USU, DES_USU_ST_LOGIN = SUBSTR(P_LOGIN, 1, 60), DES_DT = SYSDATE, LOG_ST_MENSAGEM = NULL
         WHERE LOG_IN_CODIGO = P_LOG;
    EXCEPTION
        WHEN OTHERS THEN
            W_MSG := SUBSTR(REGEXP_REPLACE(SQLERRM, '^ORA-20100: ', ''), 1, 1500);
            ROLLBACK TO SP_GFIN_DESCONC;
            UPDATE MEGA.CCS_TB_GFIN_CONC_LOG SET LOG_ST_MENSAGEM = SUBSTR('NAO DESFEZ: ' || W_MSG, 1, 1500) WHERE LOG_IN_CODIGO = P_LOG;
    END;
    COMMIT;
END CCS_P_GFIN_DESCONCILIA;
/
