-- =====================================================================================================
-- [23/09/2026 - ALEXANDRE CARVALHO] GESTOR FINANCEIRO > BI FECHAMENTO (GRUPO) - FUNDACAO
-- Dashboard de fechamento por periodo do grupo todo, a partir do briefing "BI Fechamento.xlsx".
--
-- DESCOBERTA QUE SUSTENTA O MODELO: "NF" e "PRO" do briefing NAO sao tipo de documento - sao PARES DE
-- FILIAIS. A filial com CNPJ real emite nota (NF); a filial espelho, com CNPJ fake (o proprio numero),
-- e a operacao sem nota (PRO). Ex.: 200 Quality IND (NF) x 700 PRO Quality (PRO); 401 Casa do
-- Serralheiro (NF) x 501 (PRO). Por isso toda linha do briefing e "Total | NF | PRO".
--
-- DECISOES DO ALEXANDRE (23/09):
--   1. Escopo   = todas as filiais ativas, com marcacao editavel de quem entra no total do grupo.
--   2. Metas    = cadastro proprio aqui no Gestor (tabela CCS_TB_GFIN_BI_META).
--   3. Grupo    = faturamento LIQUIDO (sem venda entre empresas do grupo), com o intragrupo a parte.
--   4. Faturar  = nota cuja ACAO gera contas a receber (GLO_ACAO.ACAO_BO_CREC='S'), saida, nao cancelada.
--      Medido em 12 meses: 247,1 MI pela regra x 153,1 MI de transferencia/remessa que fica de fora;
--      intragrupo dentro da regra = 25,5 MI -> liquido do grupo = 221,6 MI.
-- =====================================================================================================

CREATE TABLE MEGA.CCS_TB_GFIN_BI_EMPRESA (
  FIL_IN_CODIGO       NUMBER        NOT NULL,
  EMP_ST_NOME         VARCHAR2(40)  NOT NULL,   -- nome curto que aparece no painel
  EMP_ST_SIGLA        VARCHAR2(12),             -- QLT, FRD, CS, CA, AA, GA, CD...
  EMP_CH_TIPO         CHAR(3)       NOT NULL,   -- 'NF' (CNPJ real) ou 'PRO' (espelho sem nota)
  EMP_IN_FIL_PAR      NUMBER,                   -- a filial par (200<->700, 401<->501...)
  EMP_ST_SEGMENTO     VARCHAR2(10)  NOT NULL,   -- IND, VAR, CD, DIST, SERV
  EMP_BO_TOTAL_GRUPO  CHAR(1) DEFAULT 'S' NOT NULL,  -- entra no total do GRUPO?
  EMP_ST_CNPJ         VARCHAR2(20),
  EMP_IN_ORDEM        NUMBER,
  USU_IN_ALTERACAO    NUMBER,
  DT_ALTERACAO        DATE DEFAULT SYSDATE,
  CONSTRAINT CCS_PK_GFIN_BI_EMPRESA PRIMARY KEY (FIL_IN_CODIGO),
  CONSTRAINT CCS_CK_GFIN_BI_EMP_TIPO CHECK (EMP_CH_TIPO IN ('NF','PRO')),
  CONSTRAINT CCS_CK_GFIN_BI_EMP_TOT  CHECK (EMP_BO_TOTAL_GRUPO IN ('S','N'))
)
/
-- META POR EMPRESA (ou grupo) x LINHA DE PRODUTO x MES. LINHA='TOTAL' e a meta cheia da empresa.
CREATE TABLE MEGA.CCS_TB_GFIN_BI_META (
  MET_IN_ANO          NUMBER        NOT NULL,
  MET_IN_MES          NUMBER        NOT NULL,
  FIL_IN_CODIGO       NUMBER        NOT NULL,
  MET_ST_LINHA        VARCHAR2(20)  DEFAULT 'TOTAL' NOT NULL,
  MET_RE_VALOR        NUMBER(18,2)  NOT NULL,
  USU_IN_ALTERACAO    NUMBER,
  DT_ALTERACAO        DATE DEFAULT SYSDATE,
  CONSTRAINT CCS_PK_GFIN_BI_META PRIMARY KEY (MET_IN_ANO, MET_IN_MES, FIL_IN_CODIGO, MET_ST_LINHA),
  CONSTRAINT CCS_CK_GFIN_BI_META_MES CHECK (MET_IN_MES BETWEEN 1 AND 12)
)
/
INSERT ALL
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (200,'Quality Industria','QLT','NF',700,'IND',10)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (700,'Pro Quality','QLT','PRO',200,'IND',11)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (100,'Quality 100','QLT','NF',NULL,'IND',12)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (400,'Freedom Industria','FRD','NF',550,'IND',20)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (550,'Pro Freedom','FRD','PRO',400,'IND',21)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (460,'Freedom CD','CD','NF',570,'CD',30)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (570,'Pro Freedom CD','CD','PRO',460,'CD',31)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (401,'Casa do Serralheiro','CS','NF',501,'VAR',40)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (501,'Pro Casa do Serralheiro','CS','PRO',401,'VAR',41)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (402,'Casa do Aluminio','CA','NF',502,'VAR',50)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (502,'Pro Casa do Aluminio','CA','PRO',402,'VAR',51)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (403,'Arcoverde Aluminio','AA','NF',503,'VAR',60)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (503,'Pro Arcoverde','AA','PRO',403,'VAR',61)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (404,'Gravata Aluminio','GA','NF',504,'VAR',70)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (504,'Pro Gravata','GA','PRO',404,'VAR',71)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (800,'Q Distribuidora','QD','NF',NULL,'DIST',80)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (300,'JR Plasticos','JR','NF',NULL,'SERV',90)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (600,'Procolor Pintura','PC','NF',NULL,'SERV',91)
  INTO MEGA.CCS_TB_GFIN_BI_EMPRESA (FIL_IN_CODIGO,EMP_ST_NOME,EMP_ST_SIGLA,EMP_CH_TIPO,EMP_IN_FIL_PAR,EMP_ST_SEGMENTO,EMP_IN_ORDEM) VALUES (960,'NLS','NLS','NF',NULL,'SERV',92)
SELECT 1 FROM DUAL
/
UPDATE MEGA.CCS_TB_GFIN_BI_EMPRESA E
   SET E.EMP_ST_CNPJ = (SELECT A.AGN_ST_CGC FROM MEGA.GLO_AGENTES A WHERE A.AGN_TAB_IN_CODIGO=53 AND A.AGN_IN_CODIGO=E.FIL_IN_CODIGO)
/
COMMIT
/
GRANT SELECT, INSERT, UPDATE, DELETE ON MEGA.CCS_TB_GFIN_BI_EMPRESA TO PUBLIC
/
GRANT SELECT, INSERT, UPDATE, DELETE ON MEGA.CCS_TB_GFIN_BI_META TO PUBLIC
/
