CREATE OR REPLACE TYPE MEGA.CCS_TY_GFIN_BI_FAT AS OBJECT (
  SIGLA        VARCHAR2(12),
  NOME         VARCHAR2(40),
  SEGMENTO     VARCHAR2(10),
  ORDEM        NUMBER,
  FILIAIS_NF   VARCHAR2(60),
  FILIAIS_PRO  VARCHAR2(60),
  VL_TOTAL     NUMBER,
  VL_NF        NUMBER,
  VL_PRO       NUMBER,
  VL_INTRA     NUMBER,
  VL_LIQUIDO   NUMBER,
  QT_NOTAS     NUMBER,
  VL_ANT_TOTAL NUMBER,
  VL_ANT_LIQ   NUMBER,
  NO_TOTAL     CHAR(1)
)
/
CREATE OR REPLACE TYPE MEGA.CCS_TB_GFIN_BI_FAT AS TABLE OF MEGA.CCS_TY_GFIN_BI_FAT
/
CREATE OR REPLACE FUNCTION MEGA.CCS_F_GFIN_BI_FAT (
  P_DT_INI IN DATE,
  P_DT_FIM IN DATE,
  P_SEGMENTO IN VARCHAR2 DEFAULT NULL
) RETURN MEGA.CCS_TB_GFIN_BI_FAT PIPELINED IS
  V_INI_ANT DATE := ADD_MONTHS(P_DT_INI, -12);
  V_FIM_ANT DATE := ADD_MONTHS(P_DT_FIM, -12);
BEGIN
  FOR R IN (
    WITH EMP AS (
      SELECT E.FIL_IN_CODIGO FIL, E.EMP_ST_SIGLA SIGLA, E.EMP_CH_TIPO TIPO, E.EMP_ST_SEGMENTO SEG,
             MIN(E.EMP_IN_ORDEM) OVER (PARTITION BY E.EMP_ST_SIGLA) ORDEM,
             FIRST_VALUE(E.EMP_ST_NOME) OVER (PARTITION BY E.EMP_ST_SIGLA ORDER BY E.EMP_IN_ORDEM) NOME,
             E.EMP_BO_TOTAL_GRUPO NO_TOTAL
        FROM MEGA.CCS_TB_GFIN_BI_EMPRESA E
       WHERE (P_SEGMENTO IS NULL OR E.EMP_ST_SEGMENTO = P_SEGMENTO)),
    CNPJGRUPO AS (
      SELECT DISTINCT REPLACE(REPLACE(REPLACE(EMP_ST_CNPJ,'.',''),'/',''),'-','') CNPJ
        FROM MEGA.CCS_TB_GFIN_BI_EMPRESA
       WHERE LENGTH(REPLACE(REPLACE(REPLACE(EMP_ST_CNPJ,'.',''),'/',''),'-','')) = 14),
    NF AS (
      SELECT N.FIL_IN_CODIGO FIL, N.NOT_RE_VALORTOTAL VL,
             CASE WHEN EXISTS (SELECT 1 FROM MEGA.GLO_AGENTES C
                                WHERE C.AGN_TAB_IN_CODIGO = 53 AND C.AGN_IN_CODIGO = N.AGN_IN_CODIGO
                                  AND REPLACE(REPLACE(REPLACE(C.AGN_ST_CGC,'.',''),'/',''),'-','') IN (SELECT CNPJ FROM CNPJGRUPO))
                  THEN 'S' ELSE 'N' END INTRA,
             CASE WHEN N.NOT_DT_EMISSAO BETWEEN P_DT_INI AND P_DT_FIM THEN 'A' ELSE 'P' END JANELA
        FROM MEGA.VEN_NOTAFISCAL N
        JOIN MEGA.GLO_ACAO A ON A.ACAO_TAB_IN_CODIGO = N.ACAO_TAB_IN_CODIGO
                            AND A.ACAO_PAD_IN_CODIGO = N.ACAO_PAD_IN_CODIGO
                            AND A.ACAO_IN_CODIGO     = N.ACAO_IN_CODIGO
       WHERE N.NOT_CH_SITUACAO <> 'C'
         AND N.AGN_TAU_ST_CODIGO = 'C'
         AND A.ACAO_BO_CREC = 'S'
         AND A.ACAO_ST_ENTSAI = 'S'
         AND ( N.NOT_DT_EMISSAO BETWEEN P_DT_INI AND P_DT_FIM
            OR N.NOT_DT_EMISSAO BETWEEN V_INI_ANT AND V_FIM_ANT )
         AND EXISTS (SELECT 1 FROM EMP E WHERE E.FIL = N.FIL_IN_CODIGO))
    SELECT E.SIGLA, MAX(E.NOME) NOME, MAX(E.SEG) SEG, MAX(E.ORDEM) ORDEM,
           SUBSTR(LISTAGG(DISTINCT CASE WHEN E.TIPO = 'NF'  THEN TO_CHAR(E.FIL) END, ' ') WITHIN GROUP (ORDER BY 1), 1, 60) FIL_NF,
           SUBSTR(LISTAGG(DISTINCT CASE WHEN E.TIPO = 'PRO' THEN TO_CHAR(E.FIL) END, ' ') WITHIN GROUP (ORDER BY 1), 1, 60) FIL_PRO,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='A' THEN F.VL END),0), 2) VL_TOTAL,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='A' AND E.TIPO='NF'  THEN F.VL END),0), 2) VL_NF,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='A' AND E.TIPO='PRO' THEN F.VL END),0), 2) VL_PRO,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='A' AND F.INTRA='S'  THEN F.VL END),0), 2) VL_INTRA,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='A' AND F.INTRA='N'  THEN F.VL END),0), 2) VL_LIQ,
           NVL(SUM(CASE WHEN F.JANELA='A' THEN 1 END),0) QT,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='P' THEN F.VL END),0), 2) VL_ANT,
           ROUND(NVL(SUM(CASE WHEN F.JANELA='P' AND F.INTRA='N' THEN F.VL END),0), 2) VL_ANT_LIQ,
           MAX(E.NO_TOTAL) NO_TOTAL
      FROM EMP E LEFT JOIN NF F ON F.FIL = E.FIL
     GROUP BY E.SIGLA
     ORDER BY MAX(E.ORDEM)
  ) LOOP
    PIPE ROW (MEGA.CCS_TY_GFIN_BI_FAT(R.SIGLA, R.NOME, R.SEG, R.ORDEM, R.FIL_NF, R.FIL_PRO,
                                      R.VL_TOTAL, R.VL_NF, R.VL_PRO, R.VL_INTRA, R.VL_LIQ, R.QT,
                                      R.VL_ANT, R.VL_ANT_LIQ, R.NO_TOTAL));
  END LOOP;
  RETURN;
END;
/
GRANT EXECUTE ON MEGA.CCS_F_GFIN_BI_FAT TO PUBLIC
/
