CREATE OR REPLACE TYPE MEGA.CCS_TY_GFIN_BI_LIN AS OBJECT (
  LINHA VARCHAR2(60), DETALHE VARCHAR2(80), VL_TOTAL NUMBER, VL_NF NUMBER, VL_PRO NUMBER,
  QTDE NUMBER, VL_ANT NUMBER, GRUPOS NUMBER
)
/
CREATE OR REPLACE TYPE MEGA.CCS_TB_GFIN_BI_LIN AS TABLE OF MEGA.CCS_TY_GFIN_BI_LIN
/
CREATE OR REPLACE FUNCTION MEGA.CCS_F_GFIN_BI_LINHA (
  P_DT_INI IN DATE, P_DT_FIM IN DATE,
  P_LINHA  IN VARCHAR2 DEFAULT NULL,
  P_SEGMENTO IN VARCHAR2 DEFAULT NULL
) RETURN MEGA.CCS_TB_GFIN_BI_LIN PIPELINED IS
  -- Faturamento por LINHA DE PRODUTO usando a NOMENCLATURA DO MEGA: a linha e o prefixo do nome do grupo
  -- (HOM, HOB, FRN, ESC, RQL, MRL...), que cobre 97% do faturamento. Com P_LINHA preenchido, desce para
  -- os grupos daquela linha. Valor = item da nota (ITN_RE_VALORTOTAL), por isso difere um pouco do total
  -- da capa, que carrega frete e impostos.
  V_INI_ANT DATE := ADD_MONTHS(P_DT_INI, -12);
  V_FIM_ANT DATE := ADD_MONTHS(P_DT_FIM, -12);
  CURSOR C_LINHA IS
    WITH EMP AS (SELECT FIL_IN_CODIGO FIL, EMP_CH_TIPO TIPO FROM MEGA.CCS_TB_GFIN_BI_EMPRESA
                  WHERE EMP_BO_TOTAL_GRUPO='S' AND (P_SEGMENTO IS NULL OR EMP_ST_SEGMENTO = P_SEGMENTO)),
    IT AS (
      SELECT NVL(TRIM(SUBSTR(G.GRU_ST_NOME, 1, INSTR(G.GRU_ST_NOME||' - ', ' - ')-1)),'(sem grupo)') LINHA,
             NVL(G.GRU_ST_NOME,'(sem grupo)') GRUPO, E.TIPO, I.ITN_RE_VALORTOTAL VL, I.ITN_RE_QUANTIDADE QTD,
             CASE WHEN N.NOT_DT_EMISSAO BETWEEN P_DT_INI AND P_DT_FIM THEN 'A' ELSE 'P' END JANELA
        FROM MEGA.VEN_ITEMNOTAFISCAL I
        JOIN MEGA.VEN_NOTAFISCAL N ON N.ORG_IN_CODIGO=I.ORG_IN_CODIGO AND N.SEQ_IN_CODIGO=I.SEQ_IN_CODIGO AND N.NOT_IN_CODIGO=I.NOT_IN_CODIGO
        JOIN MEGA.GLO_ACAO A ON A.ACAO_TAB_IN_CODIGO=N.ACAO_TAB_IN_CODIGO AND A.ACAO_PAD_IN_CODIGO=N.ACAO_PAD_IN_CODIGO AND A.ACAO_IN_CODIGO=N.ACAO_IN_CODIGO
        JOIN EMP E ON E.FIL = N.FIL_IN_CODIGO
        JOIN MEGA.EST_PRODUTOS P ON P.PRO_TAB_IN_CODIGO=I.PRO_TAB_IN_CODIGO AND P.PRO_PAD_IN_CODIGO=I.PRO_PAD_IN_CODIGO AND P.PRO_IN_CODIGO=I.PRO_IN_CODIGO
        LEFT JOIN MEGA.EST_GRUPOS G ON G.GRU_TAB_IN_CODIGO=P.GRU_TAB_IN_CODIGO AND G.GRU_PAD_IN_CODIGO=P.GRU_PAD_IN_CODIGO
                                   AND G.GRU_IDE_ST_CODIGO=P.GRU_IDE_ST_CODIGO AND G.GRU_IN_CODIGO=P.GRU_IN_CODIGO
       WHERE N.NOT_CH_SITUACAO <> 'C' AND N.AGN_TAU_ST_CODIGO='C'
         AND A.ACAO_BO_CREC='S' AND A.ACAO_ST_ENTSAI='S'
         AND ( N.NOT_DT_EMISSAO BETWEEN P_DT_INI AND P_DT_FIM OR N.NOT_DT_EMISSAO BETWEEN V_INI_ANT AND V_FIM_ANT ))
    SELECT LINHA, CAST(NULL AS VARCHAR2(80)) DET,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' THEN VL END),0),2) VL_TOTAL,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' AND TIPO='NF'  THEN VL END),0),2) VL_NF,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' AND TIPO='PRO' THEN VL END),0),2) VL_PRO,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' THEN QTD END),0),2) QTDE,
           ROUND(NVL(SUM(CASE WHEN JANELA='P' THEN VL END),0),2) VL_ANT,
           COUNT(DISTINCT GRUPO) GRUPOS
      FROM IT GROUP BY LINHA
     HAVING NVL(SUM(CASE WHEN JANELA='A' THEN VL END),0) <> 0 OR NVL(SUM(CASE WHEN JANELA='P' THEN VL END),0) <> 0
     ORDER BY 3 DESC;
  CURSOR C_GRUPO IS
    WITH EMP AS (SELECT FIL_IN_CODIGO FIL, EMP_CH_TIPO TIPO FROM MEGA.CCS_TB_GFIN_BI_EMPRESA
                  WHERE EMP_BO_TOTAL_GRUPO='S' AND (P_SEGMENTO IS NULL OR EMP_ST_SEGMENTO = P_SEGMENTO)),
    IT AS (
      SELECT NVL(TRIM(SUBSTR(G.GRU_ST_NOME, 1, INSTR(G.GRU_ST_NOME||' - ', ' - ')-1)),'(sem grupo)') LINHA,
             NVL(G.GRU_ST_NOME,'(sem grupo)') GRUPO, E.TIPO, I.ITN_RE_VALORTOTAL VL, I.ITN_RE_QUANTIDADE QTD,
             CASE WHEN N.NOT_DT_EMISSAO BETWEEN P_DT_INI AND P_DT_FIM THEN 'A' ELSE 'P' END JANELA
        FROM MEGA.VEN_ITEMNOTAFISCAL I
        JOIN MEGA.VEN_NOTAFISCAL N ON N.ORG_IN_CODIGO=I.ORG_IN_CODIGO AND N.SEQ_IN_CODIGO=I.SEQ_IN_CODIGO AND N.NOT_IN_CODIGO=I.NOT_IN_CODIGO
        JOIN MEGA.GLO_ACAO A ON A.ACAO_TAB_IN_CODIGO=N.ACAO_TAB_IN_CODIGO AND A.ACAO_PAD_IN_CODIGO=N.ACAO_PAD_IN_CODIGO AND A.ACAO_IN_CODIGO=N.ACAO_IN_CODIGO
        JOIN EMP E ON E.FIL = N.FIL_IN_CODIGO
        JOIN MEGA.EST_PRODUTOS P ON P.PRO_TAB_IN_CODIGO=I.PRO_TAB_IN_CODIGO AND P.PRO_PAD_IN_CODIGO=I.PRO_PAD_IN_CODIGO AND P.PRO_IN_CODIGO=I.PRO_IN_CODIGO
        LEFT JOIN MEGA.EST_GRUPOS G ON G.GRU_TAB_IN_CODIGO=P.GRU_TAB_IN_CODIGO AND G.GRU_PAD_IN_CODIGO=P.GRU_PAD_IN_CODIGO
                                   AND G.GRU_IDE_ST_CODIGO=P.GRU_IDE_ST_CODIGO AND G.GRU_IN_CODIGO=P.GRU_IN_CODIGO
       WHERE N.NOT_CH_SITUACAO <> 'C' AND N.AGN_TAU_ST_CODIGO='C'
         AND A.ACAO_BO_CREC='S' AND A.ACAO_ST_ENTSAI='S'
         AND ( N.NOT_DT_EMISSAO BETWEEN P_DT_INI AND P_DT_FIM OR N.NOT_DT_EMISSAO BETWEEN V_INI_ANT AND V_FIM_ANT ))
    SELECT LINHA, GRUPO DET,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' THEN VL END),0),2) VL_TOTAL,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' AND TIPO='NF'  THEN VL END),0),2) VL_NF,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' AND TIPO='PRO' THEN VL END),0),2) VL_PRO,
           ROUND(NVL(SUM(CASE WHEN JANELA='A' THEN QTD END),0),2) QTDE,
           ROUND(NVL(SUM(CASE WHEN JANELA='P' THEN VL END),0),2) VL_ANT,
           1 GRUPOS
      FROM IT WHERE LINHA = P_LINHA GROUP BY LINHA, GRUPO
     HAVING NVL(SUM(CASE WHEN JANELA='A' THEN VL END),0) <> 0 OR NVL(SUM(CASE WHEN JANELA='P' THEN VL END),0) <> 0
     ORDER BY 3 DESC;
BEGIN
  IF P_LINHA IS NULL THEN
    FOR R IN C_LINHA LOOP
      PIPE ROW (MEGA.CCS_TY_GFIN_BI_LIN(R.LINHA, R.DET, R.VL_TOTAL, R.VL_NF, R.VL_PRO, R.QTDE, R.VL_ANT, R.GRUPOS));
    END LOOP;
  ELSE
    FOR R IN C_GRUPO LOOP
      PIPE ROW (MEGA.CCS_TY_GFIN_BI_LIN(R.LINHA, R.DET, R.VL_TOTAL, R.VL_NF, R.VL_PRO, R.QTDE, R.VL_ANT, R.GRUPOS));
    END LOOP;
  END IF;
  RETURN;
END;
/
GRANT EXECUTE ON MEGA.CCS_F_GFIN_BI_LINHA TO PUBLIC
/
